#!/bin/sh
APPDIR=`dirname $0`
GWTDIR="/usr/local/gwt"
MAPDIR="/usr/local/gwt-maps"
CLASSPATH="${APPDIR}/WebContent/WEB-INF/lib/*:${APPDIR}/JavaSource:${APPDIR}/test:${APPDIR}/bin:${GWTDIR}/*:${MAPDIR}/*"
CMPNTDIR="${APPDIR}/WebContent/JavaScript/components"
JAVAOPS="-Xmx1024M -Xms1024M"
GWTOPTIONS="-strict"

java ${JAVAOPS} -cp "${CLASSPATH}" com.google.gwt.dev.Compiler -war "${CMPNTDIR}" "$@" ${GWTOPTIONS} gov.noaa.pmel.tmap.las.InteractiveDownloadData;
java ${JAVAOPS} -cp "${CLASSPATH}" com.google.gwt.dev.Compiler -war "${CMPNTDIR}" "$@" ${GWTOPTIONS} gov.noaa.pmel.tmap.las.HelpMenu;
java ${JAVAOPS} -cp "${CLASSPATH}" com.google.gwt.dev.Compiler -war "${CMPNTDIR}" "$@" ${GWTOPTIONS} gov.noaa.pmel.tmap.las.UI;
java ${JAVAOPS} -cp "${CLASSPATH}" com.google.gwt.dev.Compiler -war "${CMPNTDIR}" "$@" ${GWTOPTIONS} gov.noaa.pmel.tmap.las.ColumnEditor;
#java ${JAVAOPS} -cp "${CLASSPATH}" com.google.gwt.dev.Compiler -war "${CMPNTDIR}" "$@" ${GWTOPTIONS} gov.noaa.pmel.tmap.las.NativeMapWidget;
java ${JAVAOPS} -cp "${CLASSPATH}" com.google.gwt.dev.Compiler -war "${CMPNTDIR}" "$@" ${GWTOPTIONS} gov.noaa.pmel.tmap.las.TestResults
java ${JAVAOPS} -cp "${CLASSPATH}" com.google.gwt.dev.Compiler -war "${CMPNTDIR}" "$@" ${GWTOPTIONS} gov.noaa.pmel.tmap.las.Correlation
java ${JAVAOPS} -cp "${CLASSPATH}" com.google.gwt.dev.Compiler -war "${CMPNTDIR}" "$@" ${GWTOPTIONS} gov.noaa.pmel.tmap.las.ClimateAnalysis
java ${JAVAOPS} -cp "${CLASSPATH}" com.google.gwt.dev.Compiler -war "${CMPNTDIR}" "$@" ${GWTOPTIONS} gov.noaa.pmel.tmap.las.DateWidgetTest
java ${JAVAOPS} -cp "${CLASSPATH}" com.google.gwt.dev.Compiler -war "${CMPNTDIR}" "$@" ${GWTOPTIONS} gov.noaa.pmel.tmap.las.SPPV
java ${JAVAOPS} -cp "${CLASSPATH}" com.google.gwt.dev.Compiler -war "${CMPNTDIR}" "$@" ${GWTOPTIONS} gov.noaa.pmel.tmap.las.PPT
