#!/bin/sh
APPDIR=`dirname $0`
GWTDIR="/usr/local/gwt"
CLASSPATH="${APPDIR}/WebContent/WEB-INF/lib/*:${APPDIR}/JavaSource:${APPDIR}/test:${APPDIR}/bin:${GWTDIR}/*"
CMPNTDIR="${APPDIR}/WebContent/JavaScript/components"
JAVAOPS="-Xmx1024M -Xms1024M"
GWTOPTIONS="-strict"

java ${JAVAOPS} -cp "${CLASSPATH}" com.google.gwt.dev.Compiler -war "${CMPNTDIR}" "$@" ${GWTOPTIONS} gov.noaa.pmel.tmap.las.InteractiveDownloadData;
java ${JAVAOPS} -cp "${CLASSPATH}" com.google.gwt.dev.Compiler -war "${CMPNTDIR}" "$@" ${GWTOPTIONS} gov.noaa.pmel.tmap.las.UI;
java ${JAVAOPS} -cp "${CLASSPATH}" com.google.gwt.dev.Compiler -war "${CMPNTDIR}" "$@" ${GWTOPTIONS} gov.noaa.pmel.tmap.las.ColumnEditor;
java ${JAVAOPS} -cp "${CLASSPATH}" com.google.gwt.dev.Compiler -war "${CMPNTDIR}" "$@" ${GWTOPTIONS} gov.noaa.pmel.tmap.las.TestResults
java ${JAVAOPS} -cp "${CLASSPATH}" com.google.gwt.dev.Compiler -war "${CMPNTDIR}" "$@" ${GWTOPTIONS} gov.noaa.pmel.tmap.las.Correlation
java ${JAVAOPS} -cp "${CLASSPATH}" com.google.gwt.dev.Compiler -war "${CMPNTDIR}" "$@" ${GWTOPTIONS} gov.noaa.pmel.tmap.las.ClimateAnalysis
java ${JAVAOPS} -cp "${CLASSPATH}" com.google.gwt.dev.Compiler -war "${CMPNTDIR}" "$@" ${GWTOPTIONS} gov.noaa.pmel.tmap.las.DateWidgetTest
java ${JAVAOPS} -cp "${CLASSPATH}" com.google.gwt.dev.Compiler -war "${CMPNTDIR}" "$@" ${GWTOPTIONS} gov.noaa.pmel.tmap.las.SPPV
java ${JAVAOPS} -cp "${CLASSPATH}" com.google.gwt.dev.Compiler -war "${CMPNTDIR}" "$@" ${GWTOPTIONS} gov.noaa.pmel.tmap.las.PPT
java ${JAVAOPS} -cp "${CLASSPATH}" com.google.gwt.dev.Compiler -war "${CMPNTDIR}" "$@" ${GWTOPTIONS} gov.noaa.pmel.tmap.las.Inventory

# This should help with the reloading problem since the modify date is managed by the complie process and there is a but.
#
# https://github.com/gwtproject/gwt/issues/9108 (even though it's fixed, it's not released).
touch WebContent/JavaScript/components/gov.noaa.pmel.tmap.las.*/gov.noaa.pmel.tmap.las.*.nocache.js

