#!/bin/sh
APPDIR=`dirname $0`;
java  -Xmx256M -cp "$APPDIR/JavaSource:$APPDIR/bin:/home/rhs/gwt-maps/gwt-maps.jar:/home/rhs/gwt/gwt-user.jar:/home/rhs/gwt/gwt-dev-linux.jar" com.google.gwt.dev.GWTCompiler -out "$APPDIR/WebContent/SlideSorter" "$@" gov.noaa.pmel.tmap.las.SlideSorter;
