#! /bin/sh
if [ ! "$FDSTEST_HOME" ] ; then
   FDSTEST_HOME=`pwd`; export FDSTEST_HOME
fi 

CP="-classpath .:$FDSTEST_HOME/lib/dods.jar"

# cd ../src/classes
# java $CP gov.noaa.pmel.tmap.ferret.test.FDSTest
java -jar fdstest.jar $1 $2 $3
