#!/bin/sh

# Last modified: $Date: 2005/02/22 07:03:14 $ 
# Revision for this file: $Revision: 1.1 $
# Release name: $Name:  $
# Original for this file: $Source: /home/ja9/tmap/FERRET_ROOT/fds/testsuite/src/makejar,v $

if [ ! "$FDSTEST_HOME" ] ; then
   FDSTEST_SRC=`dirname $0`; export FDSTEST_SRC
   FDSTEST_HOME=`cd $FDSTEST_SRC/..; pwd`; export FDSTEST_HOME
fi 

FDSTEST_LIB="$FDSTEST_HOME/lib"
TOMCAT_CMN="$FDSTEST_HOME/lib"

TOMCAT_CP="$TOMCAT_CMN/xercesImpl.jar:$TOMCAT_CMN/xml-apis.jar:$TOMCAT_CMN/servlet-api.jar"
CP="-classpath $FDSTEST_SRC:$TOMCAT_CP:$FDSTEST_LIB/dods.jar"

mkdir -p $FDSTEST_SRC/classes

echo compiling all classes...

CMD="javac -O -g -d $FDSTEST_SRC/classes $CP \

$FDSTEST_SRC/gov/noaa/pmel/tmap/ferret/test/*.java \
$FDSTEST_SRC/gov/noaa/pmel/tmap/ferret/test/dods/*.java"

if $CMD ; then
  cd $FDSTEST_SRC/classes
  jar cmf ../fdstest.mf ../../fdstest.jar gov/noaa/pmel/tmap/ferret/test
  echo compile successful. 
  echo created fdstest.jar in $FDSTEST_HOME
  rm -rf gov
else
  echo compile failed, jars not created.
  cd ..
  rm -rf classes
  echo cleaned up class files.
  exit 1;
fi

