function LASUI(){this.refs={plot:{},DW:{widgetType:null},DepthWidget:{widgetType:null},analysis:{enabled:!1},options:{plot:{},download:{},external:{}},operations:{plot:{},download:{},external:{}},auth_win:{}};this.hrefs={getProduct:{url:"ProductServer.do?"},getCategories:{url:"getCategories.do?"},getDataConstraints:{url:"getDataConstraints.do?"},getGrid:{url:"getGrid.do?"},getOperations:{url:"getOperations.do?"},getOptions:{url:"getOptions.do?"},getMetadata:{url:"getMetadata.do?"},getVariables:{url:"getVariables.do?"},
getRegions:{url:"getRegions.do?"}};this.state={extra_args:"",dataset:null,datasets:{},variables:[],operation:{plot:null,download:null,external:null},properties:{plot:[],download:[],external:[]},optiondefs:{plot:"",download:"",external:""},newproperties:{plot:[],download:[],external:[]},view:{plot:null,download:null,external:null,widgets:null},embed:!0,xybox:{},categorynames:[],analysis:{type:null,axes:{}},selection:{x:{min:null,max:null},y:{min:null,max:null},z:{min:null,max:null},t:{min:null,max:null}},
authorized:{},authorizing:{}};this.anchors={tree:"tree",output:"output",map:"MapWidget",date:"date",depth:"depth",header:"header",breadcrumb:"breadcrumb",variables:"variable_container",inputs:{maxX:"input_maxX",maxY:"input_maxY",minX:"input_minX",minY:"input_minY"},analysis:"analysis"};this.AJAX_cache={};this.request=new LASRequest;this.info_icon=document.createElement("img");this.info_icon.src="images/info.png";this.info_icon.className="LASInfoIcon";this.autoupdate=!1;for(var a in this)if(typeof this[a]==
"function")this[a].LASBind=function(a){for(var c=this,d=[],e=0,f=arguments.length;e<f;e++)d.push(arguments[e]);a=d.shift();return function(e){return c.apply(a,[e||window.event].concat(d))}}}
LASUI.prototype.initUI=function(){this.UIMask=document.createElement("DIV");this.UIMask.className="LASUIMask";this.toggleUIMask("none");document.body.appendChild(this.UIMask);this.params.openid&&(this.state.extra_args+="openid="+this.params.openid+"&");if(this.params.dsid||this.params.catid){this.state.dataset=this.params.dsid;this.state.catid=this.params.catid;this.state.lastDataset="";this.state.lastVariable="";if(this.params.varid)this.state.variable=this.params.varid;this.state.operation.plot=
this.params.plot;this.state.view.plot=this.params.view;this.autoupdate=this.params.autoupdate;(this.state.dataset!=""||this.params.catid!="")&&this.state.variable!=""?(this.submitOnLoad=!0,document.getElementById("ol_map_widget").onmouseover=null):this.submitOnLoad=!1}else{if(this.params.request){this.state.dataset=this.params.request.getDataset();this.state.lastDataset="";this.state.lastVariable="";this.state.variable=this.params.request.getVariable(0);for(this.state.variables=[];this.params.request.getVariable(this.state.variables.length);)this.state.variables.push(this.params.request.getVariable(this.state.variables.length));
this.state.operation.plot=this.params.request.getOperation();if(this.params.request.getProperty("ferret","vector_id"))this.state.variables=[],this.state.variables.push(this.params.request.getProperty("ferret","vector_id")),this.state.variable=this.params.request.getProperty("ferret","vector_id");for(var a in"xyzt"){var b="xyzt"[a];if(this.params.request.getRangeLo(b))this.state.selection[b].min=this.params.request.getRangeLo(b);if(this.params.request.getRangeHi(b))this.state.selection[b].max=this.params.request.getRangeHi(b)}this.state.view.plot=
this.params.request.getProperty("ferret","view");this.state.view.widgets=this.state.view.plot;if(this.params.request.getAnalysis(0)){this.refs.analysis.enabled=!0;this.state.analysis.enabled=!0;b="";for(a=0;a<this.params.request.getAnalysis(0).axis.length;a++)this.state.analysis.axes[this.params.request.getAnalysis(0).axis[a].type]=!0,b.indexOf(this.params.request.getAnalysis(0).axis[a].type)<0&&(b+=this.params.request.getAnalysis(0).axis[a].type),this.state.analysis.type=this.params.request.getAnalysis(0).axis[a].op,
this.state.selection[this.params.request.getAnalysis(0).axis[a].type].min=this.params.request.getAnalysis(0).axis[a].lo,this.state.selection[this.params.request.getAnalysis(0).axis[a].type].max=this.params.request.getAnalysis(0).axis[a].hi,this.state.view.widgets.indexOf(this.params.request.getAnalysis(0).axis[a].type)<0&&(this.state.view.widgets+=this.params.request.getAnalysis(0).axis[a].type),document.getElementById(this.params.request.getAnalysis(0).axis[a].op+"_analysis").selected=!0;b=="yx"&&
(b="xy");document.getElementById(b+"_analysis").selected=!0}this.request=this.params.request;this.autoupdate=this.params.autoupdate}this.submitOnLoad=!1}if(this.state.catid==null)this.state.catid=this.state.dataset;if(this.state.catid==null)this.state.catid="",this.state.dataset="";if(this.params.auth_url.length>0)for(a=0;a<this.params.auth_url.length;a++)this.authorizeURL(this.params.auth_url[a]);this.firstload=this.fullXYExtent=!0;this.expired=!1;this.refs.options.plot.DOMNode=document.getElementById("plotOptions");
this.refs.options.external.DOMNode=document.getElementById("externalOptions");this.refs.analysis.type={op:document.getElementById("analysis_op"),axes:document.getElementById("analysis_axes")};this.refs.analysis.axes={xy:document.getElementById("xy_analysis"),x:document.getElementById("x_analysis"),y:document.getElementById("y_analysis"),z:document.getElementById("z_analysis"),t:document.getElementById("t_analysis")};this.refs.analysis.type.axes.onchange=this.selectAnalysisAxis.LASBind(this,null,!0);
this.refs.analysis.type.op.onchange=this.selectAnalysisType.LASBind(this);document.all?(this.refs.analysis.type.axes.onafterclick=this.selectAnalysisAxis.LASBind(this,null,!0),this.refs.analysis.type.op.onafterclick=this.selectAnalysisType.LASBind(this)):(this.refs.analysis.type.axes.onchange=this.selectAnalysisAxis.LASBind(this,null,!0),this.refs.analysis.type.op.onchange=this.selectAnalysisType.LASBind(this));document.getElementById(this.anchors.output).addEventListener&&!document.all?document.getElementById(this.anchors.output).addEventListener("load",
this.onPlotLoad.LASBind(this),!0):document.getElementById(this.anchors.output).attachEvent&&!document.all?document.getElementById(this.anchors.output).attachEvent("load",this.onPlotLoad.LASBind(this)):document.all?document.getElementById(this.anchors.output).onreadystatechange=this.onPlotLoad.LASBind(this):document.getElementById(this.anchors.output).onload=this.onPlotLoad.LASBind(this);if(typeof mapResize!="undefined")window.onresize=mapResize;if(document.body.onresize&&typeof mapResize!="undefined")document.body.onresize=
mapResize;if(document.getElementById("categories")){this.refs.categories={};this.refs.categories.LINode=document.getElementById("categories");var c=document.createElement("INPUT");c.type="submit";c.value="Close";c.className="LASSubmitInputNode";c.onclick=this.genericHandler.LASBind(this,"this.hideCategories()");this.refs.categories.LINode.appendChild(c);this.refs.categories.LINode.appendChild(document.createElement("BR"));this.refs.categories.title=document.createElement("SPAN");this.refs.categories.title.appendChild(document.createTextNode("Select a dataset category."));
this.refs.categories.title.className="LASTreeTitleNode";this.refs.categories.ULNode=document.createElement("UL");this.refs.categories.ULNode.className="LASTreeULNode";this.refs.categories.LINode.appendChild(this.refs.categories.title);this.refs.categories.LINode.appendChild(this.refs.categories.ULNode);this.refs.categories.isExpanded=!0;a=document.all?new ActiveXObject("Microsoft.XMLHTTP"):new XMLHttpRequest(this);c=this.hrefs.getCategories.url+this.state.extra_args;a.onreadystatechange=this.AJAXhandler.LASBind(this,
a,"this.AJAX_cache['"+escape(c)+"']=req.responseText;this.setCategoryTreeNode(req.responseText,this.refs.categories,'categories');");this.AJAX_cache[c]="waiting";a.open("GET",c);a.send(null)}if((this.state.dataset!=""||this.state.catid!="")&&this.state.variable!="")this.params.catid?c=this.hrefs.getCategories.url+this.state.extra_args+"catid="+this.params.catid:this.params.dsid?c=this.hrefs.getVariables.url+this.state.extra_args+"dsid="+this.params.dsid:this.params.request&&(c=this.hrefs.getVariables.url+
this.state.extra_args+"dsid="+this.state.dataset),a=document.all?new ActiveXObject("Microsoft.XMLHTTP"):new XMLHttpRequest(this),a.onreadystatechange=this.AJAXhandler.LASBind(this,a,"this.setInitialVariable(req.responseText);"),a.open("GET",c),a.send(null)};
LASUI.prototype.setInitialVariable=function(a){a=eval("("+a+")");if(a.categories&&a.categories.status&&a.categories.status=="ok"){a=new LASGetCategoriesResponse(a);this.state.dataset=a.getDatasetID(0);this.state.datasets[this.state.dataset]=a;if(this.state.variable&&a.getCategoryType()=="dataset")for(var b=0;b<a.getCategorySize();b++)if(a.getChildID(b)==this.state.variable){this.setVariable(null,a,b);return}this.setVariable(null,a,0)}};
LASUI.prototype.printPlot=function(){var a=document.getElementById(this.anchors.output);if(a!=null)window.open(a.src+"&stream=true&stream_ID=plot_image&"+this.state.extra_args).onload=function(){this.print()}};
LASUI.prototype.linkTo=function(){var a=document.getElementById(this.anchors.output).src;a.substring(0,4)!="http"&&(a="http://"+document.location.host+document.location.pathname.replace("getUI.do?","")+a);var b="http://"+document.location.host+document.location.pathname+"?dsid="+this.state.dataset+"&varid="+this.state.variable+"&auto=true",c=document.createElement("DIV");c.className="LASPopupDIVNode";c.id="linkto_popup";var d=document.createElement("button");d.onclick=function(){document.body.removeChild(document.getElementById("linkto_popup"));
LAS.toggleUIMask("none")};d.appendChild(document.createTextNode("Close"));c.appendChild(d);c.appendChild(document.createElement("BR"));c.appendChild(document.createElement("BR"));d=document.createElement("STRONG");d.appendChild(document.createTextNode("The following URL will return you to this dataset and variable."));c.appendChild(d);c.appendChild(document.createElement("BR"));c.appendChild(document.createTextNode(b));c.appendChild(document.createElement("BR"));c.appendChild(document.createElement("BR"));
d=document.createElement("STRONG");d.appendChild(document.createTextNode("The following URL represents the plot currently shown."));c.appendChild(d);c.appendChild(document.createElement("BR"));c.appendChild(document.createTextNode(a));this.toggleUIMask("");document.body.appendChild(c)};LASUI.prototype.getMetadata=function(){window.open(this.hrefs.getMetadata.url+this.state.extra_args+"dsid="+this.state.dataset)};
LASUI.prototype.hideCategories=function(){this.refs.categories.LINode.style.display="none";this.toggleUIMask("none")};LASUI.prototype.toggleUIMask=function(a){this.UIMask.style.height=document.body.offsetHeight+100+"px";this.UIMask.style.width=document.body.offsetWidth+30+"px";this.UIMask.style.display=a};LASUI.prototype.AJAXhandler=function(){var a=arguments,b=a[1],a=a[2];b.readyState==4&&b.status==200&&eval(a)};
LASUI.prototype.setCategoryTreeNode=function(a,b,c){a=eval("("+a+")");b.category=new LASGetCategoriesResponse(a);if(b.category.getCategoryType()=="category")b.children=[];for(a=0;a<b.category.getCategorySize();a++)if(this.setCategoryTreeSubNode(b,a,c),b.category.getChild(a).remote_las){var d=document.createElement("IMG");d.src=b.category.getChild(a).remote_las.replace("auth.do","output/test.png");d.onload=this.remoteAuthSuccess.LASBind(this,b,a,!0);d.onerror="javascript:setTimeout('this.src = this.src',2000)}"}this.expand(b)};
LASUI.prototype.authorizeURL=function(a){var b=document.createElement("img");if(a)b.onerror=this.authDialog.LASBind(this,a),b.src=a.replace("auth.do","output/test.png")};
LASUI.prototype.authDialog=function(){var a=arguments[1],b=a;this.state.extra_args&&(b+="?"+this.state.extra_args);this.toggleUIMask("");var c=document.createElement("DIV");c.className="LASPopupDIVNode";var d=document.createElement("H3");d.appendChild(document.createTextNode("The LAS at "+a+" requires authentication. Do you want to continue?"));c.appendChild(d);a=document.createElement("button");a.appendChild(document.createTextNode("Ok"));a.onclick=function(){window.open(b);document.body.removeChild(this.parentNode);
LAS.toggleUIMask("none")};c.appendChild(document.createElement("BR"));c.appendChild(a);a=document.createElement("button");a.appendChild(document.createTextNode("Cancel"));a.onclick=function(){document.body.removeChild(this.parentNode);LAS.toggleUIMask("none")};c.appendChild(a);document.body.appendChild(c)};
LASUI.prototype.authorizeRemoteLAS=function(){var a=arguments,b=a[1],a=a[2],c=b.category.getChild(a).remote_las,d=c;this.state.extra_args&&(d+="?"+this.state.extra_args);this.refs.auth_win[c]=window.open(d);if(this.refs.auth_win[c]){if(!document.all)this.refs.auth_win[c].onunload=this.checkRemoteLAS.LASBind(this,b,a),this.refs.auth_win[c].onload=this.checkRemoteLAS.LASBind(this,b,a);document.all&&this.checkRemoteLAS(null,b,a)}else alert("Please turn off your pop-up blocker to allow this LAS to authenticate with remote LAS servers.")};
LASUI.prototype.checkRemoteLAS=function(){var a=arguments,b=a[1],a=a[2],c=b.category.getChild(a).remote_las;if(!this.refs.auth_ct)this.refs.auth_ct={};this.refs.auth_ct[c]||(this.refs.auth_ct[c]=0);this.refs.auth_ct[c]++;var d=document.createElement("IMG");d.onload=this.remoteAuthSuccess.LASBind(this,b,a);d.src=c.replace("auth.do","output/test.png");d.style.display="none";delete d};
LASUI.prototype.remoteAuthSuccess=function(){var a=arguments,b=a[1],c=a[2],a=a[3],d=b.category.getChild(c).remote_las;this.state.authorized[d]=!0;this.state.authorizing[d]=!1;this.refs.auth_win[d]&&this.refs.auth_win[d].close();if(!b.children[c].category&&!a)this.expand(b.children[c]),b.children[c].IMGNode.src="JavaScript/components/mozilla_blu.gif",a=document.all?new ActiveXObject("Microsoft.XMLHTTP"):new XMLHttpRequest(this),a.onreadystatechange=this.AJAXhandler.LASBind(this,a,"this.setCategoryTreeNode(req.responseText,args[3].children[args[4]],args[3].category.getChild(args[4]));",
b,c),a.open("GET",this.hrefs.getCategories.url+this.state.extra_args+"catid="+b.category.getChildID(c)),a.send(null),this.state.catid=b.category.getChildID(c)};LASUI.prototype.showInfo=function(){var a=arguments,b=a[1],a=a[2];b.category&&b.category.getChildID(a)&&(b.category.getChildChildrenType(a)=="variables"?window.open(this.hrefs.getMetadata.url+this.state.extra_args+"dsid="+b.category.getChildDatasetID(a)):window.open(this.hrefs.getMetadata.url+this.state.extra_args+"catid="+b.category.getChildID(a)))};
LASUI.prototype.setCategoryTreeSubNode=function(a,b,c){switch(a.category.getCategoryType()){case "category":this.createCategoryTreeNode(a,b,c);break;case "dataset":this.createVariableTreeNode(a,b)}};
LASUI.prototype.createCategoryTreeNode=function(a,b){if(a==this.refs.categories&&a.category.getChildChildrenType(b)=="variables")this.refs.categories.title.innerHTML="Datasets";a.children[b]={};a.children[b].LINode=document.createElement("LI");a.children[b].LINode.className="LASTreeLINode";a.children[b].IMGNode=document.createElement("IMG");a.children[b].IMGNode.id=a.category.getChildID(b);a.children[b].IMGNode.onclick=this.selectCategory.LASBind(this,a,b);a.children[b].IMGNode.src="JavaScript/ui/plus.gif";
a.children[b].IMGNode.className="LASCategoryIMGNode";a.children[b].isExpanded=!1;a.children[b].ULNode=document.createElement("ul");var c=document.createElement("TABLE");c.className="LASTreeTableNode";c.width="100%";var d=document.createElement("TBODY");d.style.padding=0;d.style.margin=0;var e=document.createElement("TR");e.style.padding=0;e.style.margin=0;var f=document.createElement("TD");f.style.verticalAlign="top";f.width="12px";f.appendChild(a.children[b].IMGNode);f.className="LASTreeTableCell";
var g=document.createElement("TD");g.style.verticalAlign="top";g.onclick=this.selectCategory.LASBind(this,a,b);g.appendChild(document.createTextNode(a.category.getChildName(b)));g.className="LASTreeTableCell";g.style.textAlign="left";e.appendChild(f);e.appendChild(g);if(a.category.getChildChildrenType(b)=="variables")f=document.createElement("TD"),a.children[b].A=document.createElement("A"),g=this.info_icon.cloneNode(!0),a.children[b].A.appendChild(g),a.children[b].A.onclick=this.showInfo.LASBind(this,
a,b),f.appendChild(a.children[b].A),f.className="LASTreeTableCell",f.width="12pt",e.appendChild(f);d.appendChild(e);c.appendChild(d);a.children[b].LINode.appendChild(c);a.children[b].LINode.appendChild(a.children[b].ULNode);(a.category.getChildChildrenType(b)=="variables"&&a.category.getChild(b).children_dsid||a.category.getChildChildrenType(b)!="variables")&&a.ULNode.appendChild(a.children[b].LINode);(this.refs.categories[a.category.getChild(b).ID]||a.category.getChild(b).ID==this.state.dataset)&&
this.selectCategory(null,a,b)};
LASUI.prototype.createVariableList=function(){var a=document.createElement("SELECT");a.onchange=this.getOperations.LASBind(this);a.className="LASVariableList";a.name="variables";if(document.all)a.id="variables";for(var b=0;b<this.state.datasets[this.state.dataset].getCategorySize();b++){var c=this.state.datasets[this.state.dataset],d=this.state.variables?this.state.variables[0]==c.getChildID(b)?!0:!1:!1,d=new Option(c.getChildName(b),c.getChildID(b),!1,d);d.value=JSON.stringify(c.getChild(b));d.id=
"/lasdata/datasets/"+c.getDatasetID()+"/variables/"+c.getChildID(b);a.options[a.length]=d}document.getElementsByName(this.anchors.variables).item(0).appendChild(a);a=a.cloneNode(!0);a.className="";a.name="";a.id="";a.style.visibility="hidden";document.getElementsByName(this.anchors.variables).item(0).appendChild(a)};
LASUI.prototype.createVariableTreeNode=function(a,b){if(!a.children)a.children=[];a.children[b]||(a.children[b]={});a.children[b].LINode=document.createElement("LI");a.children[b].LINode.style.listStyleType="none";a.children[b].LINode.style.listStyleImage="none";a.children[b].LINode.className="LASTreeLINode";a.marginLeft="5pt";if(document.all){var c="<INPUT NAME='"+a.category.getDatasetID(b)+"'>";a.children[b].INPUTNode=document.createElement(c)}else a.children[b].INPUTNode=document.createElement("INPUT"),
a.children[b].INPUTNode.name=a.category.getDatasetID(b);a.children[b].INPUTNode.type="radio";a.children[b].INPUTNode.id="/lasdata/datasets/"+a.category.getDatasetID()+"/variables/"+a.category.getChildID(b)+"_radio";a.children[b].className="LASRadioInputNode";a.children[b].INPUTNode.onclick=this.setVariable.LASBind(this,a,b);c=document.createElement("TABLE");c.width="100%";var d=document.createElement("TBODY"),e=document.createElement("TR"),f=document.createElement("TD");f.appendChild(a.children[b].INPUTNode);
f.className="LASTreeTableCell";f.width="12pt";var g=document.createElement("TD");g.innerHTML=a.category.getChildName(b);g.align="left";g.className="LASTreeTableCell";e.appendChild(f);e.appendChild(g);d.appendChild(e);c.appendChild(d);a.children[b].LINode.appendChild(c);if(this.state.variable==a.category.getChildID(b))a.children[b].INPUTNode.checked=!0;a.ULNode.appendChild(a.children[b].LINode)};
LASUI.prototype.getCategory=function(a,b){if(!a.children[b].category){var c=document.all?new ActiveXObject("Microsoft.XMLHTTP"):new XMLHttpRequest(this);c.onreadystatechange=this.AJAXhandler.LASBind(this,c,"this.setCategoryTreeNode(req.responseText,args[3].children[args[4]],args[3].category.getChild(args[4]));",a,b);c.open("GET",this.hrefs.getCategories.url+this.state.extra_args+"catid="+a.category.getChildID(b));c.send(null)}};
LASUI.prototype.getRegions=function(a,b){var c=document.all?new ActiveXObject("Microsoft.XMLHTTP"):new XMLHttpRequest(this);c.onreadystatechange=this.AJAXhandler.LASBind(this,c,"this.setRegions(req.responseText)");c.open("GET",this.hrefs.getRegions.url+this.state.extra_args+"dsid="+a+"&varid="+b);c.send(null)};LASUI.prototype.setRegions=function(a){a=eval("("+a+")");try{a.status=="ok"&&setMapRegions(a)}catch(b){}};
LASUI.prototype.onSetVariable=function(){for(var a in this.state.xpaths){var b=this.state.xpaths[a];if(b&&(b.grid_type!="scattered"&&b.grid_type!="vector"&&document.getElementsByName("variables").length==1?(this.refs.analysis.enabled&&this.showAnalysis(),document.getElementById("analysisWrapper").style.display=""):(document.getElementById("analysisWrapper").style.display="none",this.refs.analysis.enabled=!1),document.getElementById("V6")))document.getElementById("V6").href="servlets/datasets?dset="+
this.urlencode(categories+"/"+b.name)}document.getElementById("ol_map_widget").onmouseover=null;this.refresh()};
LASUI.prototype.updateVariableLists=function(){if(this.state.datasets[this.state.dataset].getCategorySize()!=1){var a=1;this.state.operations.getOperationByID(this.state.operation.plot).minvars&&(a=parseInt(this.state.operations.getOperationByID(this.state.operation.plot).minvars));var b=1;for(this.state.operations.getOperationByID(this.state.operation.plot).maxvars&&(b=parseInt(this.state.operations.getOperationByID(this.state.operation.plot).maxvars));document.getElementsByName(this.anchors.variables).length<a||
document.getElementsByName(this.anchors.variables).length<this.state.variables.length&&document.getElementsByName(this.anchors.variables).length<b&&this.firstload;){var c=document.getElementsByName(this.anchors.variables).item(0),d=c.cloneNode(!0);c.parentNode.appendChild(d)}for(;document.getElementsByName(this.anchors.variables).length>b;)c=document.getElementsByName(this.anchors.variables).item(document.getElementsByName(this.anchors.variables).length-1),c.parentNode.removeChild(c);if(document.getElementsByName(this.anchors.variables).length>
1)for(a=0;a<document.getElementsByName("del").length;a++)document.getElementsByName("del").item(a).style.display="";for(a=0;a<document.getElementsByName("add").length;a++)document.getElementsByName("add").item(a).onclick=this.addVariable.LASBind(this);for(a=0;a<document.getElementsByName("del").length;a++)document.getElementsByName("del").item(a).onclick=this.removeVariable.LASBind(this);for(a=0;a<document.getElementsByName("variables").length;a++)document.getElementsByName("variables").item(a).onchange=
this.getOperations.LASBind(this);if(document.getElementsByName("variables").length>1)for(a=0;a<document.getElementsByName("variables").length;a++)for(var e=0,b=0;b<document.getElementsByName("variables").item(a).options.length;b++)c=eval("("+document.getElementsByName("variables").item(a).options[b].value+")"),c.grid_type=="vector"?document.getElementsByName("variables").item(a).options[b].disabled=!0:e++;c=eval("("+document.getElementsByName("variables").item(0).options[document.getElementsByName("variables").item(0).selectedIndex].value+
")");if(document.getElementsByName(this.anchors.variables).length>=e||c.grid_type=="vector")for(a=0;a<document.getElementsByName("add").length;a++)document.getElementsByName("add").item(a).style.visibility="hidden";else if(c.grid_type!="vector"){for(a=0;a<document.getElementsByName("add").length;a++)document.getElementsByName("add").item(a).style.visibility="hidden";document.getElementsByName("add").item(a-1).style.visibility="visible"}if(document.getElementsByName(this.anchors.variables).length>
1)for(a=0;a<document.getElementsByName("del").length;a++)document.getElementsByName("del").item(a).style.visibility="visible";else for(a=0;a<document.getElementsByName("del").length;a++)document.getElementsByName("del").item(a).style.visibility="hidden";for(b=0;b<document.getElementsByName("variables").length;b++)for(a=0;a<document.getElementsByName("variables").item(b).options.length;a++)if(document.getElementsByName("variables").item(b).options[a].id.substr(document.getElementsByName("variables").item(b).options[a].id.lastIndexOf("/")+
1,document.getElementsByName("variables").item(b).options[a].id.length)==this.state.variables[b])document.getElementsByName("variables").item(b).options[a].selected=!0;if(this.state.operation.plot.indexOf("prop_prop")<0&&document.getElementsByName("variables").length==1)document.getElementById("analysisWrapper").style.display="";this.updateAxisLabels();typeof mapResize!="undefined"&&mapResize()}};
LASUI.prototype.updateAxisLabels=function(){if(this.state.operations.getOperationByID(this.state.operation.plot).axis_labels)if(this.state.operations.getOperationByID(this.state.operation.plot).axis_labels.label.name)document.getElementsByName("axis_labels").item(0).innerHTML=this.state.operations.getOperationByID(this.state.operation.plot).axis_labels.label.name;else for(var a=0;a<this.state.operations.getOperationByID(this.state.operation.plot).axis_labels.label.length;a++)try{document.getElementsByName("axis_labels").item(a).innerHTML=
this.state.operations.getOperationByID(this.state.operation.plot).axis_labels.label[a].name}catch(b){}else for(a=0;a<document.getElementsByName("axis_labels").length;a++)try{document.getElementsByName("axis_labels").item(a).innerHTML=""}catch(c){}};
LASUI.prototype.addVariable=function(a){var a=document.all&&!a.target?a.srcElement.parentNode:a.target.parentNode,b=a.cloneNode(!0);a.parentNode.appendChild(b);if(document.getElementsByName("variables").length>=2)for(a=0;a<document.getElementsByName("del").length;a++)document.getElementsByName("del").item(a).style.visibility="visible";for(a=0;a<b.children.length;a++){if(b.children.item(a).name=="add")b.children.item(a).onclick=this.addVariable.LASBind(this);if(b.children.item(a).name=="del")b.children.item(a).onclick=
this.removeVariable.LASBind(this);if(b.children.item(a).name=="variables")b.children.item(a).onchange=this.getOperations.LASBind(this)}for(a=b=0;a<document.getElementsByName("variables").length;a++)for(var c=b=0;c<document.getElementsByName("variables").item(a).options.length;c++)eval("("+document.getElementsByName("variables").item(a).options[c].value+")").grid_type=="vector"?document.getElementsByName("variables").item(a).options[c].disabled=!0:b++;for(a=0;a<document.getElementsByName("add").length;a++)document.getElementsByName("add").item(a).style.visibility=
"hidden";if(document.getElementsByName("variables").length<b)document.getElementsByName("add").item(a-1).style.visibility="visible";if(document.getElementsByName(this.anchors.variables).length>1)for(a=0;a<document.getElementsByName("del").length;a++)document.getElementsByName("del").item(a).style.visibility="visible";else for(a=0;a<document.getElementsByName("del").length;a++)document.getElementsByName("del").item(a).style.visibility="hidden";for(c=0;c<document.getElementsByName("variables").length;c++)for(a=
0;a<document.getElementsByName("variables").item(c).options.length;a++)if(document.getElementsByName("variables").item(c).options[a].id.substr(document.getElementsByName("variables").item(c).options[a].id.lastIndexOf("/")+1,document.getElementsByName("variables").item(c).options[a].id.length)==this.state.variables[c])document.getElementsByName("variables").item(c).options[a].selected=!0;b=a=1;try{this.state.operations.getOperationByID(this.state.operation.plot).minvars&&(a=parseInt(this.state.operations.getOperationByID(this.state.operation.plot).minvars)),
this.state.operations.getOperationByID(this.state.operation.plot).maxvars&&(b=parseInt(this.state.operations.getOperationByID(this.state.operation.plot).maxvars))}catch(d){}if(document.getElementsByName("variables").length<a||document.getElementsByName("variables").length>b)this.state.operation.plot="";this.state.operation.plot!=""&&this.updateAxisLabels();document.getElementById("analysisWrapper").style.display="none";this.refs.analysis.enabled=!1;typeof mapResize!="undefined"&&mapResize();a=document.getElementsByName("variables").item(document.getElementsByName("variables").length-
1);a.parentNode.onclick="LAS.collapseVariableLists()";a.size=a.length;a.selectedIndex=-1;a.className="LASVariableList";this.getOperations(!0)};LASUI.prototype.collapseVariableLists=function(){for(var a=0;a<document.getElementsByName("variables").length;a++)if(document.getElementsByName("variables").item(a).size=1,document.getElementsByName("variables").item(a).selectedIndex<0)document.getElementsByName("variables").item(a).selectedIndex=0};
LASUI.prototype.removeVariable=function(a){this.collapseVariableLists();document.getElementsByName("variables").length>=2&&(document.all&&!a.target?a.srcElement.parentNode.parentNode.removeChild(a.srcElement.parentNode):a.target.parentNode.parentNode.removeChild(a.target.parentNode));if(document.getElementsByName("del").length==1){for(a=0;a<document.getElementsByName("del").length;a++)document.getElementsByName("del").item(a).style.visibility="hidden";for(a=0;a<document.getElementsByName("variables").item(0).options.length;a++)document.getElementsByName("variables").item(0).options[a].disabled=
!1}for(a=0;a<document.getElementsByName("add").length;a++)document.getElementsByName("add").item(a).style.visibility="hidden";if(document.getElementsByName("variables").length<document.getElementsByName("variables").item(0).options.length)document.getElementsByName("add").item(a-1).style.visibility="visible";for(a=0;a<document.getElementsByName("variables").length;a++)document.getElementsByName("add").item(a).onclick=this.addVariable.LASBind(this),document.getElementsByName("del").item(a).onclick=
this.removeVariable.LASBind(this),document.getElementsByName("variables").item(a).onchange=this.getOperations.LASBind(this);this.updateAxisLabels();var b=a=1;try{this.state.operations.getOperationByID(this.state.operation.plot).minvars&&(a=parseInt(this.state.operations.getOperationByID(this.state.operation.plot).minvars)),this.state.operations.getOperationByID(this.state.operation.plot).maxvars&&(b=parseInt(this.state.operations.getOperationByID(this.state.operation.plot).maxvars))}catch(c){}if(document.getElementsByName("variables").length<
a||document.getElementsByName("variables").length>b)this.state.operation.plot="";if(this.state.operation.plot.indexOf("prop_prop")<0&&document.getElementsByName("variables").length==1)document.getElementById("analysisWrapper").style.display="";this.state.variables.pop();typeof mapResize!="undefined"&&mapResize();this.getOperations(!0)};
LASUI.prototype.selectCategory=function(){var a=arguments,b=a[1],a=a[2];if(b.children[a].isExpanded){this.collapse(b.children[a]);for(c=0;c<this.state.categorynames.length;c++)this.state.categorynames[c]==b.category.getChildName(a)&&this.state.categorynames.splice(c,this.state.categorynames.length-c)}else{if(b==this.refs.categories)this.state.categories={},this.state.categories[b.category.getChild(a).ID]={};for(var c=0;c<b.children.length;c++){this.collapse(b.children[c]);for(var d=0;d<this.state.categorynames.length;d++)this.state.categorynames[d]==
b.category.getChildName(c)&&this.state.categorynames.splice(d,this.state.categorynames.length-d)}b.category.getChild(a).remote_las&&this.checkRemoteLAS(null,b,a);if(b.category.getChild(a).remote_las&&!this.state.authorized[b.category.getChild(a).remote_las]){this.state.authorizing[b.category.getChild(a).remote_las]=!0;d=c=b.category.getChild(a).remote_las;this.state.extra_args&&(d+="?"+this.state.extra_args);this.refs.auth_win[c]=window.open(d);if(!this.refs.auth_win[c]){alert("Please turn off your pop-up blocker to allow this LAS to authenticate with remote LAS servers.");
return}this.refs.auth_win[c].onunload=this.checkRemoteLAS.LASBind(this,b,a);this.refs.auth_win[c].onload=this.checkRemoteLAS.LASBind(this,b,a)}if(b.category.getChild(a).remote_las)if(this.state.authorized[b.category.getChild(a).remote_las])this.expand(b.children[a]);else return;else this.expand(b.children[a]);if(b==this.refs.categories)this.state.categorynames=[];this.state.categorynames.push(b.category.getChildName(a))}if(!b.children[a].category&&!b.category.getChild(a).remote_las)b.children[a].IMGNode.src=
"JavaScript/components/mozilla_blu.gif",c=document.all?new ActiveXObject("Microsoft.XMLHTTP"):new XMLHttpRequest(this),c.onreadystatechange=this.AJAXhandler.LASBind(this,c,"this.setCategoryTreeNode(req.responseText,args[3].children[args[4]],args[3].category.getChild(args[4]));",b,a),c.open("GET",this.hrefs.getCategories.url+this.state.extra_args+"catid="+b.category.getChildID(a)),c.send(null),this.state.catid=b.category.getChildID(a)};
LASUI.prototype.setVariable=function(a){var b=arguments,c=b[1],d=b[2];if(c.category)var b=c.category.getDatasetID(d),e=c.category.getChildID(d),f=c.category.getChild(d),c=this.state.datasets[b]=c.category;else b=c.getDatasetID(d),e=c.getChildID(d),f=c.getChild(d),this.state.datasets[b]=c;this.state.variables[0]=e;this.getRegions(b,e);if(a)for(;document.getElementsByName(this.anchors.variables).length>1;)d=document.getElementsByName(this.anchors.variables).item(document.getElementsByName(this.anchors.variables).length-
1),d.parentNode.removeChild(d);if(b!=this.state.dataset){for(;document.getElementsByName(this.anchors.breadcrumb).length>1;)document.getElementsByName(this.anchors.breadcrumb).item(document.getElementsByName(this.anchors.breadcrumb).length-1).parentNode.removeChild(document.getElementsByName(this.anchors.breadcrumb).item(document.getElementsByName(this.anchors.breadcrumb).length-1));for(;document.getElementsByName(this.anchors.variables).length>1;)document.getElementsByName(this.anchors.variables).item(document.getElementsByName(this.anchors.variables).length-
1).parentNode.removeChild(document.getElementsByName(this.anchors.variables).item(document.getElementsByName(this.anchors.variables).length-1))}this.state.lastDataset=this.state.dataset;this.state.dataset=b;this.state.variable=e;if(f.grid_type=="vector")for(;document.getElementsByName(this.anchors.breadcrumb).length>1;)document.getElementsByName(this.anchors.breadcrumb).item(document.getElementsByName(this.anchors.breadcrumb).length-1).parentNode.removeChild(document.getElementsByName(this.anchors.breadcrumb).item(document.getElementsByName(this.anchors.breadcrumb).length-
1));document.getElementById("constraints").style.visibility="visible";if(document.getElementById("categories"))document.getElementById("categories").style.display="none";this.toggleUIMask("none");if(this.state.categorynames)if(this.state.categorynames.length>0)for(var g=this.state.categorynames[0],d=1;d<this.state.categorynames.length;d++)g+=" / "+this.state.categorynames[d];else g=this.state.datasets[this.state.dataset].getDatasetName();d=this.info_icon.cloneNode(!0);d.onclick=this.getMetadata.LASBind(this);
var h=document.createElement("A");h.onclick=this.removeVariable.LASBind(this);h.appendChild(document.createTextNode("X"));h.className="delvar";h.name="del";h.id="del";h.alt="Click to remove this variable.";h.title="Click to remove this variable.";h.href="javascript:";h.style.visibility="hidden";var i=document.createElement("A");i.name="add";i.className="addvar";i.id="add";i.alt="Click to add another variable.";i.title="Click to add another variable.";i.href="javascript:";i.onclick=this.addVariable.LASBind(this);
i.appendChild(document.createTextNode("+"));var j=document.createElement("a");j.id="axis_labels";j.name="axis_labels";if(c.getCategorySize()==1)i.style.visibility="hidden",h.style.visibility="hidden";if(f.grid_type=="vector")i.style.visibility="hidden",document.getElementById("analysisWrapper").style.display="none";c=document.createElement("TEXT");c.innerHTML=g;if(document.getElementsByName(this.anchors.breadcrumb).item(0)){for(;document.getElementsByName(this.anchors.breadcrumb).item(0).firstChild;)document.getElementsByName(this.anchors.breadcrumb).item(0).removeChild(document.getElementsByName(this.anchors.breadcrumb).item(0).firstChild);
document.getElementsByName(this.anchors.breadcrumb).item(0).appendChild(document.createTextNode("\u00a0"));document.getElementsByName(this.anchors.breadcrumb).item(0).appendChild(d);document.getElementsByName(this.anchors.breadcrumb).item(0).appendChild(document.createTextNode("\u00a0"));document.getElementsByName(this.anchors.breadcrumb).item(0).appendChild(c)}for(;document.getElementsByName(this.anchors.variables).item(0).firstChild;)document.getElementsByName(this.anchors.variables).item(0).removeChild(document.getElementsByName(this.anchors.variables).item(0).firstChild);
document.getElementsByName(this.anchors.variables).item(0).appendChild(i);document.getElementsByName(this.anchors.variables).item(0).appendChild(document.createTextNode("\u00a0"));document.getElementsByName(this.anchors.variables).item(0).appendChild(h);document.getElementsByName(this.anchors.variables).item(0).appendChild(document.createTextNode("\u00a0"));this.createVariableList();document.getElementsByName(this.anchors.variables).item(0).appendChild(document.createTextNode("\u00a0"));document.getElementsByName(this.anchors.variables).item(0).appendChild(j);
document.getElementById("ol_map_widget").onmouseover=null;this.newVariable=!1;if(a)if(document.all){if(a.srcElement.nodeName=="INPUT")this.newVariable=!0}else if(a.target.nodeName=="INPUT")this.newVariable=!0;this.getGrid(b,e);this.getDataConstraints(b,e)};
LASUI.prototype.getDataConstraints=function(a,b){var c=document.all?new ActiveXObject("Microsoft.XMLHTTP"):new XMLHttpRequest(this),d=this.hrefs.getDataConstraints.url+this.state.extra_args+"dsid="+a+"&varid="+b;this.AJAX_cache[d]?this.AJAX_cache[d]!="waiting"&&this.setDataConstraints(this.AJAX_cache[d]):(this.AJAX_cache[d]="waiting",c.onreadystatechange=this.AJAXhandler.LASBind(this,c,"this.AJAX_cache['"+d+"']=req.responseText;this.setDataConstraints(req.responseText);"),c.open("GET",this.hrefs.getDataConstraints.url+
this.state.extra_args+"dsid="+a+"&varid="+b),c.send(null))};
LASUI.prototype.setDataConstraints=function(a){if(a){a=eval("("+a+")");if(!this.state.constraints)this.state.constraints={};this.state.lastconstraints=this.state.constraints;this.state.constraints=a.constraints}if(this.state.lastconstraints!=this.state.constraints&&(document.getElementById("DataConstraints").innerHTML="",document.getElementById("DataConstraints").style.display="",this.state.constraints.constraint)){this.refs.constraints=[];for(a=0;a<this.state.constraints.constraint.length;a++){var b=
{},c=document.createElement("DIV");b.apply=document.createElement("INPUT");b.apply.type="checkbox";c.appendChild(b.apply);if(this.state.constraints.constraint[a].constraint.menu.content){var d=this.state.constraints.constraint[a].constraint.menu;this.state.constraints.constraint[a].constraint.menu=[];this.state.constraints.constraint[a].constraint.menu[0]=d}for(var e=0;e<this.state.constraints.constraint[a].constraint.menu.length;e++){eval("constraint."+this.state.constraints.constraint[a].constraint.menu[e].position+
' = document.createElement("SELECT")');if(this.state.constraints.constraint[a].constraint.menu[e].item.content)d=this.state.constraints.constraint[a].constraint.menu[e].item,this.state.constraints.constraint[a].constraint.menu[e].item=[],this.state.constraints.constraint[a].constraint.menu[e].item[0]=d;for(d=0;d<this.state.constraints.constraint[a].constraint.menu[e].item.length;d++){var f=document.createElement("option");f.value=this.state.constraints.constraint[a].constraint.menu[e].item[d].values;
f.appendChild(document.createTextNode(this.state.constraints.constraint[a].constraint.menu[e].item[d].content));eval("constraint."+this.state.constraints.constraint[a].constraint.menu[e].position+".appendChild(option)")}}b.lhs&&c.appendChild(b.lhs);b.ops&&c.appendChild(b.ops);if(!b.rhs)b.rhs=document.createElement("INPUT"),b.rhs.type="text";c.appendChild(b.rhs);b.type=this.state.constraints.constraint[a].constraint.type;document.getElementById("DataConstraints").appendChild(c);this.refs.constraints.push(b)}}};
LASUI.prototype.getOperations=function(a){var b=document.all?new ActiveXObject("Microsoft.XMLHTTP"):new XMLHttpRequest(this);if(!c)var c=this.state.view.plot;var c=this.hrefs.getOperations.url+this.state.extra_args,d=!1;if(a)if(a.target)try{if(a.target.options[a.target.selectedIndex].value)var e=eval("("+a.target.options[a.target.selectedIndex].value+")");if(e.grid_type=="vector"&&document.getElementsByName("add").length==1)document.getElementsByName("add").item(0).style.visibility="hidden";if(a.target==
document.getElementsByName("variables").item(0)){this.setVariable(null,this.state.datasets[this.state.dataset],document.getElementsByName("variables").item(0).selectedIndex);return}}catch(f){}else if(document.getElementsByName("variables").length==1){this.setVariable(null,this.state.datasets[this.state.dataset],document.getElementsByName("variables").item(0).selectedIndex);return}else d=!0;typeof a=="object"&&this.collapseVariableLists();this.state.xpaths=[];if(document.getElementsByName("variables").length>
0){this.state.xpaths=[];for(a=0;a<document.getElementsByName("variables").length;a++)a>0&&(c+="&"),e=document.getElementsByName("variables").item(a).selectedIndex,e<0&&(e=0),c+="xpath="+document.getElementsByName("variables").item(a).options[e].id,this.state.xpaths.push(eval("("+document.getElementsByName("variables").item(a).options[e].value+")"));try{for(a=0;a<document.getElementsByName(this.state.dataset).length;a++)if(document.getElementsByName(this.state.dataset).item(a).id==this.state.xpaths[0].ID)document.getElementsByName(this.state.dataset).item(a).checked=
!0;if(this.state.xpaths[0].grid_type=="vector")document.getElementById("analysisWrapper").style.display="none"}catch(g){}this.AJAX_cache[c]?this.AJAX_cache[c]!="waiting"&&this.setOperationList(this.AJAX_cache[c],d):(this.AJAX_cache[c]="waiting",b.onreadystatechange=this.AJAXhandler.LASBind(this,b,"this.AJAX_cache['"+c+"'] = req.responseText; this.setOperationList(req.responseText,"+d+");"),b.open("GET",c),b.send(null))}};
LASUI.prototype.setOperation=function(a){var b=arguments,c=b[1],d=b[3],e=b[4];e||(e="plot");if(e=="plot"&&c!="init")try{if(this.state.operations&&this.state.operations.getOperationByID(c).optiondef&&this.state.operations.getOperationByID(c).optiondef.IDREF)d=this.state.operations.getOperationByID(c).optiondef.IDREF}catch(f){}if(e=="plot"&&document.all&&a&&a.srcElement){for(var g=0;g<document.getElementsByName("plotType").length;g++)document.getElementsByName("plotType").item(g).checked=!1;a.srcElement.checked=
!0}this.state.operation[e]=c;this.refs.options[e].DOMNode.innerHTML="";b=b[2];this.state.view[e]=b;this.updateVariableLists();document.getElementsByName("variables");document.getElementsByName("variables").length==1&&this.state.xpaths[0].grid_type!="vector"&&this.state.xpaths[0].grid_type!="scattered"&&c!="prop_prop_plot"?document.getElementById("analysisWrapper").style.display="":(this.refs.analysis.enabled=!1,document.getElementById("analysisWrapper").style.display="none");if(this.refs.analysis.enabled)for(var h in this.state.analysis.axes)if(b.indexOf(h)<
0)b+=h,this.refs.analysis.axes[h].selected=!0;else{this.refs.analysis.axes[h].selected=!1;if(h=="x"||h=="y")this.refs.analysis.axes.xy.selected=!1;delete this.state.analysis.axes[h]}this.state.view.widgets=b;for(c=0;c<document.getElementById("productButtons").childNodes.length;c++)for(e=0;e<document.getElementById("productButtons").childNodes[c].childNodes.length;e++)try{document.getElementById("productButtons").childNodes[c].className="top_link_disabled",document.getElementById("productButtons").childNodes[c].onclick=
function(){}}catch(i){}for(g=0;g<this.state.operations.getOperationCount();g++)document.getElementById(this.state.operations.getOperationName(g))&&this.state.operations.hasInterval(this.state.operations.getOperationID(g),b)&&this.setOperationNode(this.state.operations.getOperationID(g),this.state.operations.getOperationName(g));this.updateConstraints(b);this.state.operations.getOperationByID(this.state.operation.plot).optiondef?this.state.operations.getOperationByID(this.state.operation.plot).optiondef.IDREF?
this.getOptions(this.state.operations.getOperationByID(this.state.operation.plot).optiondef.IDREF,"plot",!0):(document.getElementById("plotOptionsButton").className="top_link_disabled",document.getElementById("plotOptionsButton").onclick=function(){}):(document.getElementById("plotOptionsButton").className="top_link_disabled",document.getElementById("plotOptionsButton").onclick=function(){});this.state.lastVariable=this.state.variable;this.state.lastDataset=this.state.dataset;if(d)this.getOptions(d,
"plot",!1);else if(this.newVariable&&this.onSetVariable)this.onSetVariable();this.firstload=!1};LASUI.prototype.genericHandler=function(a,b){b&&eval(b)};
LASUI.prototype.setOperationList=function(a,b){var c=eval("("+a+")");if(c.operations.error=="No operations found."&&this.state.view.plot.length>1)return this.state.view.plot=this.state.view.plot[0],this.setVisualization(this.state.view.plot,"view"),null;this.state.operations=new LASGetOperationsResponse(c);for(c=0;c<document.getElementById("productButtons").childNodes.length;c++)for(var d=0;d<document.getElementById("productButtons").childNodes[c].childNodes.length;d++)try{document.getElementById("productButtons").childNodes[c].className=
"top_link_disabled",document.getElementById("productButtons").childNodes[c].onclick=function(){}}catch(e){}!this.state.operations.response.operations.error&&!b&&this.setDefaultProductMenu();document.getElementsByName("variables");for(c=0;c<document.getElementById("productButtons").childNodes.length;c++)for(d=0;d<document.getElementById("productButtons").childNodes[c].childNodes.length;d++)try{document.getElementById("productButtons").childNodes[c].className="top_link_disabled",document.getElementById("productButtons").childNodes[c].onclick=
function(){}}catch(f){}if(b){for(c=0;c<this.state.operations.getOperationCount();c++){var g=d=1;try{this.state.operations.getOperation(c).minvars&&(d=parseInt(this.state.operations.getOperation(c).minvars)),this.state.operations.getOperation(c).maxvars&&(g=parseInt(this.state.operations.getOperation(c).maxvars))}catch(h){}this.state.operations.hasInterval(this.state.operations.getOperationID(c),this.state.view.plot)&&document.getElementsByName("variables").length<=g&&document.getElementsByName("variables").length>=
d&&this.setOperationNode(this.state.operations.getOperationID(c),this.state.operations.getOperationName(c))}g=d=1;try{this.state.operations.getOperationByID(this.state.operation.plot).minvars&&(d=parseInt(this.state.operations.getOperationByID(this.state.operation.plot).minvars)),this.state.operations.getOperationByID(this.state.operation.plot).maxvars&&(g=parseInt(this.state.operations.getOperationByID(this.state.operation.plot).maxvars))}catch(i){}(document.getElementsByName("variables").length>
g||document.getElementsByName("variables").length<d)&&this.setVisualization(this.state.view.plot,"varct")}else for(c=0;c<this.state.operations.getOperationCount();c++){g=d=1;try{this.state.operations.getOperation(c).minvars&&(d=parseInt(this.state.operations.getOperation(c).minvars)),this.state.operations.getOperation(c).maxvars&&(g=parseInt(this.state.operations.getOperation(c).maxvars))}catch(j){}this.state.operations.hasInterval(this.state.operations.getOperationID(c),this.state.view.plot)&&document.getElementsByName("variables").length<=
g&&document.getElementsByName("variables").length>=d&&this.setOperationNode(this.state.operations.getOperationID(c),this.state.operations.getOperationName(c))}};LASUI.prototype.refresh=function(){if(!this.updating)this.autoupdate?(this.newVariable=this.submitOnLoad=!1,this.makeRequest()):this.showUpdateLink()};
LASUI.prototype.setOperationNode=function(a,b){var c=document.getElementById(b);if(c)c.className="top_link",c.onclick=this.doProductIconClick.LASBind(this,a);if(this.refs.analysis.enabled||!this.state.grid.hasAxis("t")||this.state.view.plot.indexOf("t")>=0||this.state.operation.plot.indexOf("prop_prop")>=0)document.getElementById("Animation").className="top_link_disabled",document.getElementById("Animation").onclick=function(){};if(this.state.operation.plot.indexOf("prop_prop")>=0)document.getElementById("Plot to Google Earth").className=
"top_link_disabled",document.getElementById("Plot to Google Earth").onclick=function(){}};
LASUI.prototype.doProductIconClick=function(){var a=arguments[1];this.state.operation.external=a;this.state.view.external=this.state.view.plot;this.toggleUIMask("");if(this.state.operations.getOperationByID(a))this.state.operations.getOperationByID(a).optiondef?(this.getOptions(this.state.operations.getOperationByID(a).optiondef.IDREF,"external",!0),this.refs.options.external.DOMNode.style.display=""):(this.refs.options.external.DOMNode.style.display="none",this.toggleUIMask("none"),this.makeRequest({},
"external"))};
LASUI.prototype.getGrid=function(a,b){var c=this.hrefs.getGrid.url+this.state.extra_args+"dsid="+a+"&varid="+b;if(this.AJAX_cache[c])this.AJAX_cache[c]!="waiting"&&this.setGrid(this.AJAX_cache[c]);else{this.AJAX_cache[c]="waiting";var d=document.all?new ActiveXObject("Microsoft.XMLHTTP"):new XMLHttpRequest(this);d.onreadystatechange=this.AJAXhandler.LASBind(this,d,"this.AJAX_cache['"+c+"']=req.responseText;this.setGrid(req.responseText);");d.open("GET",this.hrefs.getGrid.url+this.state.extra_args+"dsid="+
a+"&varid="+b);d.send(null)}};LASUI.prototype.setGrid=function(a){if(a=="")return alert("This dataset is currently unavailable."),-1;eval("var response = ("+a+")");if(this.state.grid)this.state.lastgrid=this.clone(this.state.grid);this.state.grid=new LASGetGridResponse(response);if(!this.state.lastgrid)this.state.lastgrid=this.clone(this.state.grid);this.getOperations()};
LASUI.prototype.setDefaultProductMenu=function(){for(;document.getElementById("plotTypes").firstChild;)document.getElementById("plotTypes").removeChild(document.getElementById("plotTypes").firstChild);var a=null;document.getElementsByName("variables");for(var b in this.state.operations.getAllOperationTypes())for(var c in this.state.operations.getOperationsByType(b))for(var d in this.state.operations.getOperationIntervals(c))if(this.state.grid.hasView(d)&&this.state.operations.getOperationIntervals(c)[d].type==
b){var e=parseInt(this.state.operations.getOperationByID(c).minvars);e||(e=1);parseInt(this.state.operations.getOperationByID(c).maxvars);try{this.state.operations.getOperationByID(c)["default"]&&this.state.operations.getOperationByID(c).category=="visualization"&&this.state.operations.hasInterval(c,d)&&this.state.datasets[this.state.dataset].getCategorySize()>=e&&(document.getElementById(b)||this.setProductTypeNode(b),!a||this.state.operation.plot==c&&this.state.view.plot==d?a=this.setProductNode(c,
d,this.state.operations.getOperationIntervals(c)[d].title):document.getElementById(c+"_"+d)||this.setProductNode(c,d,this.state.operations.getOperationIntervals(c)[d].title))}catch(f){}}if(a)a.onclick(null),a.checked="checked",a.selected=!0;this.refs.analysis.enabled&&this.showAnalysis()};LASUI.prototype.setProductTypeNode=function(a){var b=document.createElement("LI"),c=document.createElement("TEXT");c.innerHTML="<b>"+a+"</b>";b.className="LASPlotCategory";b.id=a;b.appendChild(c);document.getElementById("plotTypes").appendChild(b)};
LASUI.prototype.setProductNode=function(a,b,c){var d=this.state.operations.getOperationByID(a).optiondef?this.state.operations.getOperationByID(a).optiondef.IDREF:"",e=document.createElement("LI");e.className="LASPlotType";c=document.createTextNode(c);if(document.all)var f=document.createElement("<INPUT type='radio' name='plotType'/>");else f=document.createElement("INPUT"),f.name="plotType";f.type="radio";f.className="LASRadioInputNode";f.value=a;f.id=a+"_"+b;f.onselect=this.setOperation.LASBind(this,
a,b,d,"plot");f.onclick=this.setOperation.LASBind(this,a,b,d,"plot");e.appendChild(f);e.appendChild(c);document.getElementById("plotTypes").appendChild(e);return f};
LASUI.prototype.onPlotLoad=function(){for(var a=window.frames[this.anchors.output].document.location.search.replace("?","").split("&"),b=0;b<a.length;b++)if(a[b].substr(0,3)=="xml")var c=new LASRequest(unescape(a[b].substr(4,a[b].length)).replace(/\+/g," "));if(c){if(c.getXMLText&&!isFeatureEditing()){var a=parseFloat(c.getRangeLo("x")),b=parseFloat(c.getRangeLo("y")),d=parseFloat(c.getRangeHi("x")),e=parseFloat(c.getRangeHi("y")),f=parseFloat(c.getRangeLo("t")),g=parseFloat(c.getRangeLo("z")),h=
parseFloat(c.getRangeHi("t")),i=parseFloat(c.getRangeHi("z"));!d&&a&&(d=a);!e&&a&&(e=b);!i&&g&&(i=g);!h&&f&&(h=f);if(g>i)var j=g,g=i,i=j;b&&a&&e&&d&&setMapCurrentSelection(b,e,a,d);if(a)this.state.selection.x.min=a;if(d)this.state.selection.x.max=d;if(b)this.state.selection.y.min=b;if(e)this.state.selection.y.max=e;if(g)this.state.selection.z.min=g;if(i)this.state.selection.z.max=i;if(f)this.state.selection.t.min=f;if(h)this.state.selection.t.max=h}this.request=c;this.uirequest="xml="+this.urlencode(this.request.getXMLText())}if(document.getElementById("wait"))document.getElementById("wait").style.visibility=
"hidden";if(document.getElementById("wait_msg"))document.getElementById("wait_msg").style.display="none";if(document.getElementById("output"))document.getElementById("output").style.visibility="visible";if(document.getElementById("update"))document.getElementById("update").className="top_link",document.getElementById("update").style.color=""};
LASUI.prototype.onPlotUnload=function(){if(document.getElementById("wait"))document.getElementById("wait").style.visibility="visible";if(document.getElementById("wait_msg"))document.getElementById("wait_msg").style.display="";if(document.getElementById("output"))document.getElementById("output").style.visibility="hidden"};
LASUI.prototype.roundGrid=function(a){var b={x:{min:0,max:0},y:{min:0,max:0}};b.x.min=Math.round(a.x.min*1E3)/1E3;b.x.max=Math.round(a.x.max*1E3)/1E3;b.y.min=Math.round(a.y.min*1E3)/1E3;b.y.max=Math.round(a.y.max*1E3)/1E3;return b};
LASUI.prototype.updateConstraints=function(a){if(this.state.grid){for(a==null&&a!=""?a=this.state.view.widgets:this.state.view.widgets=a;document.getElementById("Date").firstChild;)document.getElementById("Date").removeChild(document.getElementById("Date").firstChild);for(;document.getElementById("Depth").firstChild;)document.getElementById("Depth").removeChild(document.getElementById("Depth").firstChild);var b=!1;if(this.state.lastDataset!=this.state.dataset||this.resetXY)b=!0,this.resetXY=!1,this.state.selectGlobal=
!1;this.initialized||(b=!0);a.indexOf("x")>=0&&a.indexOf("y")>=0?this.initXYSelect("xy",b):a.indexOf("x")>=0&&a.indexOf("y")<0?this.initXYSelect("x",b):a.indexOf("x")<0&&a.indexOf("y")>=0?this.initXYSelect("y",b):a.indexOf("x")<0&&a.indexOf("y")<0&&this.initXYSelect("pt",b);for(b=0;b<this.state.grid.response.grid.axis.length;b++)a.indexOf(this.state.grid.response.grid.axis[b].type)<0?this.state.datasets[this.state.dataset].getChildByID(this.state.variable).grid_type!="scattered"&&!this.refs.analysis.enabled&&
this.state.operation.plot!="prop_prop_plot"?eval("this.init"+this.state.grid.response.grid.axis[b].type.toUpperCase()+"Constraint('point',reset)"):eval("this.init"+this.state.grid.response.grid.axis[b].type.toUpperCase()+"Constraint('range',reset)"):eval("this.init"+this.state.grid.response.grid.axis[b].type.toUpperCase()+"Constraint('range',reset)");if(this.refs.analysis.enabled)for(b=0;b<this.state.grid.response.grid.axis.length;b++)if(a.indexOf(this.state.grid.response.grid.axis[b].type)<0)switch(this.state.grid.response.grid.axis[b].type){case "z":this.refs.DepthWidget[this.refs.DepthWidget.widgetType][1].disabled=
!0;break;case "t":this.refs.DW.widgetType?this.refs.DW.disable("hi"):this.refs.DW[1].disabled=!0}else switch(this.state.grid.response.grid.axis[b].type){case "z":this.refs.DepthWidget[this.refs.DepthWidget.widgetType][1].disabled=!1;break;case "t":this.refs.DW.widgetType?this.refs.DW.enable("hi"):this.refs.DW[1].disabled=!1}this.initialized=!0;this.updating||(this.autoupdate?this.makeRequest():this.showUpdateLink());this.updating=!1;this.state.lastgrid=this.clone(this.state.grid)}};
LASUI.prototype.initXYSelect=function(a,b){this.state.grid.getAxis("x")&&this.state.grid.getAxis("y")&&b?(setMapTool(a),setMapDataExtent(parseFloat(this.state.grid.getLo("y")),parseFloat(this.state.grid.getHi("y")),parseFloat(this.state.grid.getLo("x")),parseFloat(this.state.grid.getHi("x")),parseFloat(this.state.grid.getDelta("x")))):setMapTool(a)};LASUI.prototype.initXConstraint=function(){};LASUI.prototype.initYConstraint=function(){};
LASUI.prototype.initZConstraint=function(a,b){for(;document.getElementById("Depth").firstChild;)document.getElementById("Depth").removeChild(document.getElementById("Depth").firstChild);if(!this.state.selection.z.min)this.state.selection.z.min=this.state.grid.getLo("z");if(!this.state.selection.z.max)this.state.selection.z.max=this.state.grid.getHi("z");if(this.state.grid.hasMenu("z")&&(b||this.refs.DepthWidget.widgetType!="menu")){this.refs.DepthWidget.menu=[document.createElement("SELECT"),document.createElement("SELECT")];
this.refs.DepthWidget.widgetType="menu";for(var c=0;c<this.refs.DepthWidget[this.refs.DepthWidget.widgetType].length;c++){for(var d=null,e=0;e<this.state.grid.getMenu("z").length;e++){var f=document.createElement("OPTION");f.value=this.state.grid.getMenu("z")[e][1];f.className="LASOptionNode";f.appendChild(document.createTextNode(this.state.grid.getMenu("z")[e][0]));if(c==1&&parseFloat(this.state.grid.getMenu("z")[e][0])>=this.state.selection.z.max)if(d){if(parseFloat(this.state.grid.getMenu("z")[e][0])<
d)f.selected=!0,d=parseFloat(this.state.grid.getMenu("z")[e][0])}else f.selected=!0,d=parseFloat(this.state.grid.getMenu("z")[e][0]);if(c==0&&parseFloat(this.state.grid.getMenu("z")[e][0])<=this.state.selection.z.min)if(d){if(parseFloat(this.state.grid.getMenu("z")[e][0])>d)f.selected=!0,d=parseFloat(this.state.grid.getMenu("z")[e][0])}else f.selected=!0,d=parseFloat(this.state.grid.getMenu("z")[e][0]);this.refs.DepthWidget[this.refs.DepthWidget.widgetType][c].appendChild(f)}this.refs.DepthWidget[this.refs.DepthWidget.widgetType][c].className=
"LASSelectNode";this.refs.DepthWidget[this.refs.DepthWidget.widgetType][c].onchange=this.handleDepthRangeChange.LASBind(this)}}if(this.state.grid.hasArange("z")&&(b||this.refs.DepthWidget.widgetType!="arange")){this.refs.DepthWidget.arange=[document.createElement("SELECT"),document.createElement("SELECT")];this.refs.DepthWidget.widgetType="arange";for(c=0;c<this.refs.DepthWidget[this.refs.DepthWidget.widgetType].length;c++){this.refs.DepthWidget[this.refs.DepthWidget.widgetType][c].className="LASSelectNode";
var d=null,g=parseFloat(this.state.grid.getDelta("z"));g<0&&(g*=-1);for(e=parseFloat(this.state.grid.getLo("z"));e<=parseFloat(this.state.grid.getHi("z"));e+=g){f=document.createElement("option");f.value=e;f.className="LASOptionNode";f.appendChild(document.createTextNode(e));if(c==1&&e>=this.state.selection.z.max)if(d){if(e<d)f.selected=!0,d=e}else f.selected=!0,d=e;if(c==0&&e<=this.state.selection.z.min)if(d){if(e>d)f.selected=!0,d=e}else d=e,f.selected=!0;this.refs.DepthWidget[this.refs.DepthWidget.widgetType][c].appendChild(f)}this.refs.DepthWidget[this.refs.DepthWidget.widgetType][c].onchange=
this.handleDepthRangeChange.LASBind(this)}}switch(a){case "range":c=document.createElement("STRONG");c.appendChild(document.createTextNode("Minimum Depth ("+this.state.grid.getAxis("z").units+"):"));document.getElementById("Depth").appendChild(c);document.getElementById("Depth").appendChild(this.refs.DepthWidget[this.refs.DepthWidget.widgetType][0]);document.getElementById("Depth").appendChild(document.createElement("BR"));c=document.createElement("STRONG");c.appendChild(document.createTextNode("Maximum Depth ("+
this.state.grid.getAxis("z").units+"):"));document.getElementById("Depth").appendChild(c);document.getElementById("Depth").appendChild(this.refs.DepthWidget[this.refs.DepthWidget.widgetType][1]);document.getElementById("Depth").style.display="";break;case "point":c=document.createElement("STRONG"),c.appendChild(document.createTextNode("Depth ("+this.state.grid.getAxis("z").units+"):")),document.getElementById("Depth").appendChild(c),document.getElementById("Depth").appendChild(this.refs.DepthWidget[this.refs.DepthWidget.widgetType][0]),
document.getElementById("Depth").style.display=""}};
LASUI.prototype.initTConstraint=function(a,b){for(document.getElementById("Date").style.display="";document.getElementById("Date").firstChild;)document.getElementById("Date").removeChild(document.getElementById("Date").firstChild);if(!this.state.selection.t)this.state.selection.t={min:null,max:null};switch(this.state.grid.getDisplayType("t")){case "widget":if(b||!this.refs.DW)if(b||this.refs.DW.widgetType!="DateWidget")this.refs.DW=new DateWidget(this.state.grid.getLo("t"),this.state.grid.getHi("t"),
this.state.grid.getMinuteInterval("t")),this.refs.DW.callback=this.handleDateRangeChange.LASBind(this);var c="";this.state.grid.getAxis("t").monthNeeded=="true"&&(c+="M");this.state.grid.getAxis("t").dayNeeded=="true"&&(c+="D");this.state.grid.getAxis("t").yearNeeded=="true"&&(c+="Y");if(this.state.grid.getAxis("t").hourNeeded=="true"||this.state.grid.getAxis("t").hoursNeeded=="true")c+="T";switch(a){case "range":for(;document.getElementById("Date").firstChild;)document.getElementById("Date").removeChild(document.getElementById("Date").firstChild);
var d=document.createElement("STRONG");d.appendChild(document.createTextNode("Date Range:"));document.getElementById("Date").appendChild(d);d=document.createElement("DIV");d.id="DWAnchor";document.getElementById("Date").appendChild(d);this.refs.DW.render("DWAnchor",c,c);break;case "point":for(;document.getElementById("Date").firstChild;)document.getElementById("Date").removeChild(document.getElementById("Date").firstChild);d=document.createElement("STRONG");d.appendChild(document.createTextNode("Date:"));
document.getElementById("Date").appendChild(d);d=document.createElement("DIV");d.id="DWAnchor";document.getElementById("Date").appendChild(d);this.refs.DW.render("DWAnchor",c,c);this.refs.DW.render("DWAnchor",c)}break;case "menu":if(b||!this.refs.DW)if(b||this.refs.DW[0].tagName!="select"){this.refs.DW=[document.createElement("select"),document.createElement("select")];for(c=0;c<this.refs.DW.length;c++){this.refs.DW[c].onchange=this.handleDateRangeChange.LASBind(this);this.refs.DW[c].className="LASSelectNode";
for(d=0;d<this.state.grid.getMenu("t").length;d++){var e=document.createElement("option");e.value=this.state.grid.getMenu("t")[d][1];e.className="LASOptionNode";e.appendChild(document.createTextNode(this.state.grid.getMenu("t")[d][0]));if(c==1&&d>=this.state.grid.getMenu("t").length-1)e.selected=!0;if(c==0&&d==0)e.selected=!0;this.refs.DW[c].appendChild(e)}}}switch(a){case "range":d=document.createElement("STRONG");d.appendChild(document.createTextNode("Start Date:"));document.getElementById("Date").appendChild(d);
document.getElementById("Date").appendChild(this.refs.DW[0]);document.getElementById("Date").appendChild(document.createElement("BR"));c=document.createElement("STRONG");c.appendChild(document.createTextNode("End Date:"));document.getElementById("Date").appendChild(c);document.getElementById("Date").appendChild(this.refs.DW[1]);break;case "point":d=document.createElement("STRONG"),d.appendChild(document.createTextNode("Date:")),document.getElementById("Date").appendChild(d),document.getElementById("Date").appendChild(this.refs.DW[0])}}};
LASUI.prototype.showUpdateLink=function(){this.expired=!0;document.getElementById("update").style.color="#f5ed52";document.getElementById("update").className="top_link";if(document.getElementById("wait"))document.getElementById("wait").style.visibility="hidden";if(document.getElementById("wait_msg"))document.getElementById("wait_msg").style.display="none";if(document.getElementById("output"))document.getElementById("output").style.visibility="visible";this.newVariable&&this.makeRequest()};
LASUI.prototype.toggleAutoUpdate=function(a,b){(this.autoupdate=b)&&this.expired&&this.makeRequest();a=a||event;a.stopPropagation?a.stopPropagation():a.cancelBubble=!0;return!1};
LASUI.prototype.makeRequest=function(a,b){b||(b="plot");if(!this.updating||this.expired){if(b=="plot"&&this.state.operation.plot=="init")return this.getOperations(this.state.dataset,this.state.variable,this.state.view.plot),null;if(!document.getElementById(this.state.operation.plot+"_"+this.state.view.plot))return null;document.getElementById("output").height="100%";document.getElementById("output").width="100%";document.getElementById("update").style.visibility="visible";this.request=null;this.uirequest=
"";this.request=new LASRequest("");this.state.view.download=this.state.view.plot;this.state.view.external=this.state.view.plot;this.request.removeVariables();this.request.removeConstraints();this.request.setOperation(this.state.operation[b]);this.uirequest+="dsid="+this.state.dataset;this.uirequest+="&catid="+this.state.catid;this.uirequest+="&varid="+this.state.variable;this.uirequest+="&plot="+this.state.operation.plot;this.uirequest+="&view="+this.state.view.plot;for(var c in this.state.properties[b])typeof this.state.properties[b][c]!=
"function"&&typeof this.state.properties[b][c]=="object"&&this.request.setProperty(this.state.properties[b][c].type,c,this.urlencode(this.state.properties[b][c].value));this.request.setProperty("ferret","view",this.state.view[b]);this.request.removeRegion();c=[];this.state.variables=[];for(var d=0;d<document.getElementsByName("variables").length;d++){var e=document.getElementsByName("variables").item(d).selectedIndex>=0?document.getElementsByName("variables").item(d).selectedIndex:0;c[document.getElementsByName("variables").item(d).options[e].id]=
eval("("+document.getElementsByName("variables").item(d).options[e].value+")");e=eval("("+document.getElementsByName("variables").item(d).options[e].value+")");this.state.variables.push(e);this.request.addVariable(this.state.dataset,e.ID)}for(xpath in c)c[xpath].grid_type=="vector"&&(this.request.removeVariables(),this.request.addVariable(this.state.dataset,c[xpath].variable[0].IDREF),this.request.addVariable(this.state.dataset,c[xpath].variable[1].IDREF),this.request.addProperty("ferret","vector_name",
c[xpath].name),this.request.addProperty("ferret","vector_id",c[xpath].ID));this.request.addRegion();if(this.refs.analysis.enabled&&this.state.analysis.enabled){c={label:this.state.analysis.name+" "+this.state.datasets[this.state.dataset].getChildByID(this.state.variable).name,axis:[]};for(var f in this.state.analysis.axes)if(d={type:f,op:this.state.analysis.type},this.state.grid.hasAxis(f)){d={type:f,op:this.state.analysis.type};switch(f){case "x":d.lo=getMapXlo();d.hi=getMapXhi();break;case "y":d.lo=
getMapYlo();d.hi=getMapYhi();break;case "t":this.state.grid.hasMenu("t")?(d.lo=this.refs.DW[0].value,d.hi=this.refs.DW[1].value):(d.lo=this.refs.DW.getDate1_Ferret(),d.hi=this.refs.DW.getDate2_Ferret());break;case "z":d.lo=this.refs.DepthWidget[this.refs.DepthWidget.widgetType][0].value,d.hi=this.refs.DepthWidget[this.refs.DepthWidget.widgetType][1].value}c.axis.push(d)}c.axis.length>0&&this.state.analysis.name!="None"&&this.request.setAnalysis(0,c)}for(f=0;f<this.state.grid.response.grid.axis.length;f++)if(!this.refs.analysis.enabled||
!this.state.analysis.enabled||!this.state.analysis.axes[this.state.grid.response.grid.axis[f].type])switch(this.state.grid.response.grid.axis[f].type){case "x":this.state.view[b].indexOf("x")>=0||this.state.datasets[this.state.dataset].getChildByID(this.state.variable).grid_type=="scattered"||this.state.operation.plot.indexOf("prop_prop")>=0?this.request.addRange("x",getMapXlo(),getMapXhi()):this.request.addRange("x",(getMapXlo()+getMapXhi())/2,(getMapXlo()+getMapXhi())/2);break;case "y":this.state.view[b].indexOf("y")>=
0||this.state.datasets[this.state.dataset].getChildByID(this.state.variable).grid_type=="scattered"||this.state.operation.plot.indexOf("prop_prop")>=0?this.request.addRange("y",getMapYlo(),getMapYhi()):this.request.addRange("y",(getMapYlo()+getMapYhi())/2,(getMapYlo()+getMapYhi())/2);break;case "t":this.state.view[b].indexOf("t")>=0||this.state.datasets[this.state.dataset].getChildByID(this.state.variable).grid_type=="scattered"||this.state.operation.plot.indexOf("prop_prop")>=0?this.state.grid.hasMenu("t")?
this.request.addRange("t",this.refs.DW[0].value,this.refs.DW[1].value):this.request.addRange("t",this.refs.DW.getDate1_Ferret(),this.refs.DW.getDate2_Ferret()):this.state.grid.hasMenu("t")?this.request.addRange("t",this.refs.DW[0].value):this.request.addRange("t",this.refs.DW.getDate1_Ferret());break;case "z":this.state.view[b].indexOf("z")>=0||this.state.datasets[this.state.dataset].getChildByID(this.state.variable).grid_type=="scattered"||this.state.operation.plot.indexOf("prop_prop")>=0?this.request.addRange("z",
this.refs.DepthWidget[this.refs.DepthWidget.widgetType][0].value,this.refs.DepthWidget[this.refs.DepthWidget.widgetType][1].value):this.request.addRange("z",this.refs.DepthWidget[this.refs.DepthWidget.widgetType][0].value)}if(this.refs.constraints)for(f=0;f<this.refs.constraints.length;f++)if(this.refs.constraints[f].apply.checked)switch(this.refs.constraints[f].type){case "text":this.request.addTextConstraint(this.urlencode(this.refs.constraints[f].lhs.value),this.urlencode(this.refs.constraints[f].ops.value),
this.urlencode(this.refs.constraints[f].rhs.value));break;case "variable":this.request.addVariableConstraint(this.urlencode(this.state.dataset),this.urlencode(this.refs.constraints[f].lhs.value),this.urlencode(this.refs.constraints[f].ops.value),this.urlencode(this.refs.constraints[f].rhs.value))}document.getElementById("ol_map_widget").onmouseover=null;f=b=="external"&&this.state.operation.external=="Interactive_Download"?"height=500,width=400,status=no,toolbar=no,menubar=no,location=no":"";if(this.state.embed&&
b=="plot"){if(document.getElementById("wait"))document.getElementById("wait").style.visibility="visible";if(document.getElementById("wait_msg"))document.getElementById("wait_msg").style.display="";document.getElementById(this.anchors.output).style.visibility="hidden";document.getElementById(this.anchors.output).src=this.hrefs.getProduct.url+this.state.extra_args+"xml="+this.urlencode(this.request.getXMLText())}else window.open(this.hrefs.getProduct.url+this.state.extra_args+"xml="+this.urlencode(this.request.getXMLText()),
null,f)}this.updating=!1;this.state.lastVariable=this.state.variable;this.state.lastDataset=this.state.dataset;this.newVariable=this.state.selectGlobal=!1;if(this.state.grid.hasAxis("x")&&this.state.grid.hasAxis("y")&&Math.abs(getMapXhi()-getMapXlo()-(this.state.grid.getHi("x")-this.state.grid.getLo("x")))<10&&Math.abs(getMapYhi()-getMapYlo()-(this.state.grid.getHi("y")-this.state.grid.getLo("y")))<5)this.state.selectGlobal=!0;if(b=="plot")this.expired=!1,document.getElementById("update").style.color=
"",document.getElementById("print").className="top_link",document.getElementById("linkto").className="top_link",this.uirequest="xml="+this.urlencode(this.request.getXMLText())};LASUI.prototype.cancelRequest=function(){try{document.getElementById(this.anchors.output).src=this.hrefs.getProduct.url+this.state.extra_args+"xml="+this.urlencode(this.request.getXMLText())+"&cancel=true"}catch(a){}};
LASUI.prototype.getOptions=function(a,b,c){var d=this.hrefs.getOptions.url+this.state.extra_args+"opid="+a,e=document.createElement("INPUT"),f=document.createElement("INPUT");e.type="submit";e.value="OK";e.className="LASSubmitInputNode";var g="this.setChangedOptions('"+b+"');this.hideOptions('"+b+"')";b!="plot"&&(g+=";this.makeRequest({},'"+b+"')");e.onclick=this.genericHandler.LASBind(this,g);f.type="submit";f.value="Cancel";f.className="LASSubmitInputNode";f.onclick=this.genericHandler.LASBind(this,
"this.cancelChangedOptions('"+b+"');this.hideOptions('"+b+"')");g=document.createElement("INPUT");g.type="submit";g.onclick=this.genericHandler.LASBind(this,"this.resetOptions('"+b+"')");g.name="Reset";for(g.value="Reset";this.refs.options[b].DOMNode.firstChild;)this.refs.options[b].DOMNode.removeChild(this.refs.options[b].DOMNode.firstChild);this.refs.options[b].DOMNode.appendChild(e);this.refs.options[b].DOMNode.appendChild(g);this.refs.options[b].DOMNode.appendChild(f);this.AJAX_cache[d]?this.AJAX_cache[d]!=
"waiting"&&this.setOptionList(this.AJAX_cache[d],this.refs.options[b].DOMNode,b,c):(this.AJAX_cache[d]="waiting",e=document.all?new ActiveXObject("Microsoft.XMLHTTP"):new XMLHttpRequest(this),e.onreadystatechange=this.AJAXhandler.LASBind(this,e,"this.AJAX_cache['"+d+"']=req.responseText;this.setOptionList(req.responseText,args[3],args[4],args[5]);",this.refs.options[b].DOMNode,b,c),e.open("GET",this.hrefs.getOptions.url+this.state.extra_args+"opid="+a),e.send(null))};
LASUI.prototype.setOptionList=function(a,b,c,d){document.getElementById("plotOptionsButton").className="top_link";document.getElementById("plotOptionsButton").onclick=showPlotOptions;var e=document.createElement("TABLE");e.style.margin="-4pt";e.style.marginLeft="6pt";e.cellpadding="0";e.cellspacing="0";var f=document.createElement("TBODY");e.appendChild(f);b.appendChild(e);a=eval("("+a+")");this.refs.options[c].options=new LASGetOptionsResponse(a);if(a=this.refs.options[c].options.getOptionCount())for(b=
0;b<a;b++)this.setOptionTRNode(this.refs.options[c].options.getOptionID(b),f,c,d);if(this.newVariable&&this.onSetVariable)this.onSetVariable()};
LASUI.prototype.setOptionTRNode=function(a,b,c,d){if(!this.refs.options.cache)this.refs.options.cache={};if(!this.refs.options.cache[a]||d){this.refs.options.cache[a]=this.refs.options[c].options.getOptionByID(a);this.refs.options.cache[a].TRNode=document.createElement("TR");this.refs.options.cache[a].TD1=document.createElement("TD");this.refs.options.cache[a].TD1.width="45%";this.refs.options.cache[a].TD1.appendChild(document.createTextNode(this.refs.options.cache[a].title));this.refs.options.cache[a].TD2=
document.createElement("TD");if(this.refs.options.cache[a].menu){this.refs.options.cache[a].SELECTNode=document.createElement("SELECT");this.refs.options.cache[a].SELECTNode.setAttribute("name",a);this.state.properties[c][a]||(this.state.properties[c][a]={type:"ferret",value:this.refs.options.cache[a].menu.item[0].values,default_value:this.refs.options.cache[a].menu.item[0].values});for(d=0;d<this.refs.options.cache[a].menu.item.length;d++){var e=document.createElement("OPTION");e.value=this.refs.options.cache[a].menu.item[d].values;
e.appendChild(document.createTextNode(this.refs.options.cache[a].menu.item[d].content));this.refs.options.cache[a].SELECTNode.appendChild(e)}this.refs.options.cache[a].TD2.appendChild(this.refs.options.cache[a].SELECTNode)}else this.state.properties[c][a]||(this.state.properties[c][a]={type:"ferret",value:"",default_value:""}),this.refs.options.cache[a].INPUTNode=document.createElement("INPUT"),this.refs.options.cache[a].INPUTNode.type="text",this.refs.options.cache[a].INPUTNode.className="LASTextInputNode",
this.refs.options.cache[a].TD2.appendChild(this.refs.options.cache[a].INPUTNode);this.refs.options.cache[a].TD3=document.createElement("TD");this.refs.options.cache[a].A=document.createElement("A");this.refs.options.cache[a].A.appendChild(this.info_icon.cloneNode(!0));this.refs.options.cache[a].A.onclick=this.showOptionInfo.LASBind(this,this.refs.options.cache[a].help);this.refs.options.cache[a].TD3.appendChild(this.refs.options.cache[a].A);this.refs.options.cache[a].TRNode.appendChild(this.refs.options.cache[a].TD1);
this.refs.options.cache[a].TRNode.appendChild(this.refs.options.cache[a].TD2);this.refs.options.cache[a].TRNode.appendChild(this.refs.options.cache[a].TD3)}if(c=="plot"){if(this.refs.options.cache[a].SELECTNode)this.refs.options.cache[a].SELECTNode.onchange=this.setOption.LASBind(this,a,"plot",this.refs.options.cache[a]);if(this.refs.options.cache[a].INPUTNode)this.refs.options.cache[a].INPUTNode.onchange=this.setOption.LASBind(this,a,"plot",this.refs.options.cache[a]);b.appendChild(this.refs.options.cache[a].TRNode)}else{d=
this.clone(this.refs.options.cache[a]);d.TD2.innerHTML="";if(d.SELECTNode)d.SELECTNode.onchange=this.setOption.LASBind(this,a,c,d),d.SELECTNode.selectedIndex=this.refs.options.cache[a].SELECTNode.selectedIndex,d.SELECTNode.onchange({target:d.SELECTNode},a,c,d),d.TD2.appendChild(d.SELECTNode);if(d.INPUTNode)d.INPUTNode.onchange=this.setOption.LASBind(this,a,c,d),d.INPUTNode.value=this.refs.options.cache[a].INPUTNode.value,d.INPUTNode.onchange({target:d.INPUTNode},a,c,d),d.TD2.appendChild(d.INPUTNode);
for(;d.TRNode.firstChild;)d.TRNode.removeChild(d.TRNode.firstChild);d.TRNode.appendChild(d.TD1);d.TRNode.appendChild(d.TD2);d.TRNode.appendChild(this.refs.options.cache[a].TD3);b.appendChild(d.TRNode)}};LASUI.prototype.showOptions=function(a){if(this.refs.options[a].options)this.toggleUIMask(""),document.getElementById(a+"Options").style.display=""};LASUI.prototype.hideOptions=function(a){this.refs.options[a].DOMNode.style.display="none";this.toggleUIMask("none")};
LASUI.prototype.resetOptions=function(a){if(a!="plot"){for(;this.refs.options[a].DOMNode.firstChild;)this.refs.options[a].DOMNode.removeChild(this.refs.options[a].DOMNode.firstChild);this.getOptions(this.state.operations.getOperationByID(this.state.operation[a]).optiondef.IDREF,a,!0);this.showOptions(a)}else for(id in this.state.properties[a]){this.state.newproperties[a][id]=this.state.properties[a][id].value!=this.state.properties[a][id].default_value?this.copyProperty(this.state.properties[a][id],
this.state.properties[a][id].default_value):null;var b=this.refs.options.cache[id];if(b.SELECTNode)for(var c=0;c<b.SELECTNode.options.length;c++){if(b.SELECTNode.options[c].value==this.state.properties[a][id].default_value)b.SELECTNode.selectedIndex=c,b.SELECTNode.options[c].selected=!0}else if(b.INPUTNode)b.INPUTNode.value=this.state.properties[a][id].default_value}};LASUI.prototype.copyProperty=function(a,b){return{type:"ferret",value:b,default_value:a.default_value}};
LASUI.prototype.showOptionInfo=function(a,b){this.optionInfo&&this.optionInfo.parentNode&&this.optionInfo.parentNode.removeChild(this.optionInfo);this.optionInfo=document.createElement("DIV");document.body.appendChild(this.optionInfo);this.optionInfo.className="LASPopupDIVNode";this.optionInfo.style.left=this.optionInfo.offsetLeft+3+"px";this.optionInfo.style.top=this.optionInfo.offsetTop+3+"px";var c=document.createElement("INPUT"),d=document.createElement("CENTER");c.type="submit";c.onclick=this.hideOptionInfo.LASBind(this,
this.optionInfo);c.name="Close";c.value="Close";this.optionInfo.innerHTML+=b;d.appendChild(c);this.optionInfo.appendChild(d)};LASUI.prototype.hideOptionInfo=function(a,b){b.parentNode.removeChild(b)};
LASUI.prototype.setOption=function(a){var b=arguments,c=b[1];if(a.target)var d=a.target;else if(a.srcElement)d=a.srcElement;else return;var e=b[2],f=this.state.properties[e][c].value;this.state.newproperties[e][c]=b[3].SELECTNode?d.options[d.selectedIndex].value!=f?this.copyProperty(this.state.properties[e][c],d.options[d.selectedIndex].value):null:d.value!=f?this.copyProperty(this.state.properties[e][c],d.value):null};
LASUI.prototype.setChangedOptions=function(a){var b=0,c;for(c in this.state.newproperties[a])this.state.newproperties[a][c]!=null&&(this.state.properties[a][c]=this.state.newproperties[a][c],b++);!this.updating&&a=="plot"&&b>0&&(this.autoupdate?this.makeRequest():this.showUpdateLink());this.state.newproperties={plot:[],external:[],download:[]}};
LASUI.prototype.cancelChangedOptions=function(){for(var a in this.state.properties)for(var b in this.state.properties[a])if(this.refs.options.cache[b]&&this.state.properties[a][b])if(this.refs.options.cache[b].SELECTNode)for(var c=0;c<this.refs.options.cache[b].SELECTNode.length;c++){if(this.refs.options.cache[b].SELECTNode.options[c].value==this.state.properties[a][b].value)this.refs.options.cache[b].SELECTNode.selectedIndex=c,this.refs.options.cache[b].SELECTNode.options[c].selected=!0}else if(this.refs.options.cache[b].INPUTNode)this.refs.options.cache[b].INPUTNode.value=
this.state.properties[a][b].value};LASUI.prototype.onafterdraw=function(){this.state.selection.x.min=getMapXlo();this.state.selection.x.max=getMapXhi();this.state.selection.y.min=getMapYlo();this.state.selection.y.max=getMapYhi();this.updating||(this.autoupdate?this.makeRequest():this.showUpdateLink())};LASUI.prototype.handleDepthRangeChange=function(){this.updating||(this.autoupdate?this.makeRequest():this.showUpdateLink())};
LASUI.prototype.handleDepthChange=function(){this.updating||(this.autoupdate?this.makeRequest():this.showUpdateLink())};LASUI.prototype.handleDateRangeChange=function(){this.updating||(this.autoupdate?this.makeRequest():this.showUpdateLink())};LASUI.prototype.handleDateChange=function(){this.updating||(this.autoupdate?this.makeRequest():this.showUpdateLink())};
LASUI.prototype.collapseRootNodes=function(){var a=arguments;this.refs[a[1]].isExpanded?this.collapse(this.refs[a[1]]):(this.expand(this.refs[a[1]]),a[1]!="categories"&&this.collapse(this.refs.categories))};
LASUI.prototype.showAnalysis=function(){if(this.state.datasets[this.state.dataset].getChildByID(this.state.variable).grid_type!="scattered"){this.refs.analysis.enabled=!0;document.getElementById("Animation").className="top_link_disabled";document.getElementById("Animation").onclick=function(){};for(var a in this.refs.analysis.axes)try{this.refs.analysis.axes[a].selected=!1,document.getElementById("analysis_axes").removeChild(this.refs.analysis.axes[a])}catch(b){}document.getElementById("analysis_axes").selectedIndex=
0;this.state.grid.hasAxis("x")&&this.state.grid.hasAxis("y")&&document.getElementById("analysis_axes").appendChild(this.refs.analysis.axes.xy);for(var c=0;c<this.state.grid.response.grid.axis.length;c++)document.getElementById("analysis_axes").appendChild(this.refs.analysis.axes[this.state.grid.response.grid.axis[c].type.toLowerCase()]);c=document.getElementById(this.anchors.analysis).style.display="";for(a in this.state.analysis.axes)c+=a;c=="yx"&&(c="xy");if(document.getElementById(c+"_analysis"))document.getElementById(c+
"_analysis").selected=!0;else if(document.getElementById("analysis_axes").value!="")for(a=0;a<document.getElementById("analysis_axes").value.length;a++)this.state.analysis.axes[document.getElementById("analysis_axes").value[a]]=!0;this.state.analysis.type&&this.selectAnalysisType(null,this.state.analysis.type,!0)}};
LASUI.prototype.hideAnalysis=function(){this.refs.analysis.enabled=!1;document.getElementById(this.anchors.analysis).style.display="none";for(var a=0;a<this.state.grid.response.grid.axis.length;a++)if(this.state.view.plot.indexOf(this.state.grid.response.grid.axis[a].type.toLowerCase())<0)switch(this.state.grid.response.grid.axis[a].type.toLowerCase()){case "z":this.refs.DepthWidget[this.refs.DepthWidget.widgetType][1].disabled=!1;break;case "t":this.refs.DW.widgetType?this.refs.DW.enable("hi"):this.refs.DW[1].disabled=
!1}this.updateConstraints(this.state.view.plot)};
LASUI.prototype.selectAnalysisType=function(a){var b=!1;if(a)this.state.analysis.type=document.getElementById("analysis_op").options[document.getElementById("analysis_op").selectedIndex].value,this.state.analysis.name=document.getElementById("analysis_op").options[document.getElementById("analysis_op").selectedIndex].innerHTML;this.state.analysis.enabled=!1;if(this.state.analysis.type&&this.state.analysis.axes){for(var c in this.state.analysis.axes)if(this.state.analysis.axes[c])this.state.analysis.enabled=!0;
if(this.state.analysis.enabled){var d="";for(c in this.state.analysis.axes)this.state.analysis.axes[c]&&(d+=c),!this.state.view.widgets.indexOf(c)>=0&&this.state.analysis.axes[c]&&(this.state.view.widgets+=c),this.state.view.plot.indexOf(c)>=0&&this.state.analysis.axes[c]&&(b=!0)}}this.state.analysis.enabled?(this.updateConstraints(this.state.view.widgets),b&&this.setVisualization(d,"analysis")):this.updateConstraints(this.state.view.plot)};
LASUI.prototype.selectAnalysisAxis=function(a,b,c){if(b==""||b=={}||b==null)b=document.getElementById("analysis_axes").options[document.getElementById("analysis_axes").selectedIndex].value;this.state.analysis.axes={};var d=!1;this.state.view.widgets=this.state.view.plot;if(c==!0||a)for(a=0;a<b.length;a++)this.state.analysis.axes[b.charAt(a)]=!0,this.state.view.plot.indexOf(b.charAt(a))>=0&&this.state.analysis.type&&(d=!0),this.state.view.widgets.indexOf(b.charAt(a))<0&&this.state.analysis.type&&(this.state.view.widgets+=
b.charAt(a));this.state.analysis.enabled=!1;if(this.state.analysis.type&&this.state.analysis.axes)for(var e in this.state.analysis.axes)if(this.state.analysis.axes[e])this.state.analysis.enabled=!0;this.state.analysis.enabled?this.updateConstraints(this.state.view.widgets):this.updateConstraints(this.state.view.plot);d&&this.setVisualization(b,"analysis")};
LASUI.prototype.setVisualization=function(a,b){var c=!1,d="",d=this.state.view.plot;if(b=="analysis")switch(a){case "xy":this.state.grid.hasAxis("t")?d="t":this.state.grid.hasAxis("z")&&(d="z");break;case "t":this.state.grid.hasAxis("x")&&this.state.grid.hasAxis("y")?d="xy":this.state.grid.hasAxis("z")&&(d="z");break;case "z":this.state.grid.hasAxis("x")&&this.state.grid.hasAxis("y")?d="xy":this.state.grid.hasAxis("t")&&(d="t");break;case "x":this.state.grid.hasAxis("y")?d="y":this.state.grid.hasAxis("t")?
d="t":this.state.grid.hasAxis("z")&&(d="z");break;case "y":this.state.grid.hasAxis("x")?d="x":this.state.grid.hasAxis("t")?d="t":this.state.grid.hasAxis("z")&&(d="z")}if(document.getElementById(this.state.operation.plot+"_"+d)&&b!="analysis")document.getElementById(this.state.operation.plot+"_"+d).checked=!0,document.getElementById(this.state.operation.plot+"_"+d).onclick({srcElement:document.getElementById(this.state.operation.plot+"_"+d)});else{for(var e=0;e<document.getElementsByName("plotType").length;e++){var f=
document.getElementsByName("plotType").item(e).id.substr(document.getElementsByName("plotType").item(e).id.lastIndexOf("_")+1,document.getElementsByName("plotType").item(e).id.length),g=document.getElementsByName("plotType").item(e).id.substr(0,document.getElementsByName("plotType").item(e).id.lastIndexOf("_")),h=document.getElementsByName("variables").length,i=1,j=1;this.state.operations.getOperationByID(g).minvars&&(i=parseInt(this.state.operations.getOperationByID(g).minvars));this.state.operations.getOperationByID(g).maxvars&&
(j=parseInt(this.state.operations.getOperationByID(g).maxvars));if(!c)switch(b){case "view":if(f==d&&this.state.operation.plot==g)document.getElementsByName("plotType").item(e).checked=!0,document.getElementsByName("plotType").item(e).onclick({srcElement:document.getElementsByName("plotType").item(e)}),c=!0;break;case "varct":if(h<=j&&h>=i&&this.state.operation.plot==g)document.getElementsByName("plotType").item(e).checked=!0,document.getElementsByName("plotType").item(e).onclick({srcElement:document.getElementsByName("plotType").item(e)}),
c=!0;break;case "analysis":if(i==1&&f==d){document.getElementsByName("plotType").item(e).checked=!0;this.state.operation.plot=g;this.state.view.plot=d;this.state.view.widgets=d+a;this.updateConstraints(this.state.view.widgets);try{this.state.operations.getOperationByID(g).optiondef.IDREF&&this.getOptions(this.state.operations.getOperationByID(g).optiondef.IDREF,"plot",!1)}catch(l){}c=!0}}}if(!c&&b!="analysis")for(e=0;e<document.getElementsByName("plotType").length;e++)if(f=document.getElementsByName("plotType").item(e).id.substr(document.getElementsByName("plotType").item(e).id.lastIndexOf("_"),
document.getElementsByName("plotType").item(e).id.length),g=document.getElementsByName("plotType").item(e).id.substr(0,document.getElementsByName("plotType").item(e).id.lastIndexOf("_")),h=document.getElementsByName("variables").length,j=i=1,this.state.operations.getOperationByID(g).minvars&&(i=parseInt(this.state.operations.getOperationByID(g).minvars)),this.state.operations.getOperationByID(g).maxvars&&(j=parseInt(this.state.operations.getOperationByID(g).maxvars)),!c)switch(b){case "view":if(f==
d)document.getElementsByName("plotType").item(e).checked=!0,document.getElementsByName("plotType").item(e).onclick({srcElement:document.getElementsByName("plotType").item(e)}),c=!0;break;case "varct":if(h<=j&&h>=i)document.getElementsByName("plotType").item(e).checked=!0,document.getElementsByName("plotType").item(e).onclick({srcElement:document.getElementsByName("plotType").item(e)}),c=!0;break;default:if(f==d||h<=j&&h>=i)var k=document.getElementsByName("plotType").item(e).id}}if(b!="analysis")if(!c&&
k){if(document.getElementById(k))document.getElementById(k).checked=!0,document.getElementById(k).onclick({srcElement:document.getElementById("defaultPlot")})}else if(!c)document.getElementsByName("plotType").item(0).checked=!0,document.getElementsByName("plotType").item(0).onclick({srcElement:document.getElementsByName("plotType").item(0)});if(b=="analysis")this.refs.analysis.axes[a].selected=!0};
LASUI.prototype.collapse=function(a){if(a.ULNode)a.ULNode.style.display="none";if(a.IMGNode&&a.IMGNode.src!="JavaScript/ui/plus.gif")a.IMGNode.src="JavaScript/ui/plus.gif";a.isExpanded=!1};LASUI.prototype.expand=function(a){if(a.ULNode)a.ULNode.style.display="";if(a.IMGNode&&a.IMGNode.src!="JavaScript/ui/minus.gif")a.IMGNode.src="JavaScript/ui/minus.gif";a.isExpanded=!0};
LASUI.prototype.clone=function(a){if(typeof a!="object")return a;if(a.cloneNode)return a.cloneNode(!0);var b={},c;for(c in a)b[c]=this.clone(a[c]);return b};LASUI.prototype.urlencode=function(a){var b={},a=a.toString(),c=function(a,b,c){var g=[],g=c.split(a);return g.join(b)};b["!"]="%21";b["%20"]="+";a=encodeURIComponent(a);for(search in b)replace=b[search],a=c(search,replace,a);return a.replace(/(\%([a-z0-9]{2}))/g,function(a,b,c){return"%"+c.toUpperCase()})};
LASUI.prototype.pause=function(a){var b=new Date,c=null;do c=new Date;while(c-b<a)};LASUI.prototype.checkPopups=function(){};
