var whitespace="\n\r\t ",quotes="\"'";function convertEscapes(a){var b;for(b=-1;a.indexOf("&lt;",b+1)>-1;){b=a.indexOf("&lt;",b+1);var c=a.substr(0,b);c+="<";c+=a.substr(b+4,a.length);a=c}for(b=-1;a.indexOf("&gt;",b+1)>-1;){b=a.indexOf("&gt;",b+1);c=a.substr(0,b);c+=">";c+=a.substr(b+4,a.length);a=c}for(b=-1;a.indexOf("&amp;",b+1)>-1;){b=a.indexOf("&amp;",b+1);c=a.substr(0,b);c+="&";c+=a.substr(b+5,a.length);a=c}return a}
function convertToEscapes(a){for(var b=-1;a.indexOf("&",b+1)>-1;){b=a.indexOf("&",b+1);var c=a.substr(0,b);c+="&amp;";c+=a.substr(b+1,a.length);a=c}for(b=-1;a.indexOf("<",b+1)>-1;){b=a.indexOf("<",b+1);c=a.substr(0,b);c+="&lt;";c+=a.substr(b+1,a.length);a=c}for(b=-1;a.indexOf(">",b+1)>-1;){b=a.indexOf(">",b+1);c=a.substr(0,b);c+="&gt;";c+=a.substr(b+1,a.length);a=c}return a}
function _displayElement(a,b){if(a!=null)if(a.nodeType=="ELEMENT"){var c=a.tagName,e="";e="<"+c;for(var f=a.getAttributeNames(),g=0;g<f.length;g++){var h=f[g];e=e+" "+h+"=";e=e+'"'+a.getAttribute(h)+'"'}e+=">";b+=e;if(a.children!=null){a=a.children;for(g=0;g<a.length;g++){e=a[g];if(e.nodeType=="COMMENT")b=b+"<!--"+e.content+"--\>";else if(e.nodeType=="TEXT"){f=trim(e.content,true,true);b+=e.content}else if(e.nodeType=="CDATA"){f=trim(e.content,true,true);b=b+"<![CDATA["+f+"]]\>"}else b=_displayElement(e,
b)}}return b=b+"</"+c+">"}}function firstWhiteChar(a,b){if(isEmpty(a))return-1;for(;b<a.length;)if(whitespace.indexOf(a.charAt(b))!=-1)return b;else b++;return a.length}function isEmpty(a){return a==null||a.length==0}function trim(a,b,c){if(isEmpty(a))return"";if(b==null)b=true;if(c==null)c=true;var e=0,f=0,g=0,h=0;if(b==true)for(;g<a.length&&whitespace.indexOf(a.charAt(g++))!=-1;)e++;if(c==true)for(h=a.length-1;h>=e&&whitespace.indexOf(a.charAt(h--))!=-1;)f++;return a.substring(e,a.length-f)}
function XMLDoc(a,b){this.topNode=null;this.errFn=b;this.createXMLNode=_XMLDoc_createXMLNode;this.error=_XMLDoc_error;this.getUnderlyingXMLText=_XMLDoc_getUnderlyingXMLText;this.handleNode=_XMLDoc_handleNode;this.hasErrors=false;this.insertNodeAfter=_XMLDoc_insertNodeAfter;this.insertNodeInto=_XMLDoc_insertNodeInto;this.loadXML=_XMLDoc_loadXML;this.parse=_XMLDoc_parse;this.parseAttribute=_XMLDoc_parseAttribute;this.parseDTD=_XMLDoc_parseDTD;this.parsePI=_XMLDoc_parsePI;this.parseTag=_XMLDoc_parseTag;
this.removeNodeFromTree=_XMLDoc_removeNodeFromTree;this.replaceNodeContents=_XMLDoc_replaceNodeContents;this.selectNode=_XMLDoc_selectNode;this.selectNodeText=_XMLDoc_selectNodeText;this.source=a;if(this.parse())return this.topNode!=null?this.error("expected close "+this.topNode.tagName):true}function _XMLDoc_createXMLNode(a){return(new XMLDoc(a,this.errFn)).docNode}
function _XMLDoc_error(a){this.hasErrors=true;if(this.errFn)this.errFn("ERROR: "+a);else this.onerror&&this.onerror("ERROR: "+a);return 0}
function _XMLDoc_getTagNameParams(a,b){var c=-1,e,f=a.indexOf("["),g=[];if(f>=0){e=a.indexOf("]");if(e>=0)c=a.substr(f+1,e-f-1);else b.error("expected ] near "+a);a=a.substr(0,f);if(isNaN(c)&&c!="*"){g=c.substr(1,c.length-1);g=g.split("=");if(g[1]){f=g[1].indexOf('"');g[1]=g[1].substr(f+1,g[1].length-1);e=g[1].indexOf('"');if(e>=0)g[1]=g[1].substr(0,e);else b.error('expected " near '+a)}c=-1}else if(c=="*")c=-1}return[a,c,g[0],g[1]]}
function _XMLDoc_getUnderlyingXMLText(){var a="";a+='<?xml version="1.0"?>';if(this.docNode!=null)return a=_displayElement(this.docNode,a)}
function _XMLDoc_handleNode(a){if(a.nodeType=="COMMENT"&&this.topNode!=null)return this.topNode.addElement(a);else if(a.nodeType=="TEXT"||a.nodeType=="CDATA")return this.topNode==null?trim(a.content,true,false)==""?true:this.error("expected document node, found: "+a):this.topNode.addElement(a);else if(a.nodeType=="OPEN"||a.nodeType=="SINGLE"){var b=false;if(this.topNode==null){this.docNode=a;a.parent=null;b=true}else b=this.topNode.addElement(a);if(b&&a.nodeType!="SINGLE")this.topNode=a;a.nodeType=
"ELEMENT";return b}else if(a.nodeType=="CLOSE")if(this.topNode==null)return this.error("close tag without open: "+a.toString());else if(a.tagName!=this.topNode.tagName)return this.error("expected closing "+this.topNode.tagName+", found closing "+a.tagName);else this.topNode=this.topNode.getParent();return true}
function _XMLDoc_insertNodeAfter(a,b){var c=this.getUnderlyingXMLText();a=a.getUnderlyingXMLText();a=c.lastIndexOf(a)+a.length;var e=c.substr(0,a);e+=b.getUnderlyingXMLText();e+=c.substr(a);return new XMLDoc(e,this.errFn)}function _XMLDoc_insertNodeInto(a,b){var c=this.getUnderlyingXMLText();a=a.getUnderlyingXMLText();var e=a.indexOf(">")+1;a=c.indexOf(a)+e;e=c.substr(0,a);e+=b.getUnderlyingXMLText();e+=c.substr(a);return new XMLDoc(e,this.errFn)}
function _XMLDoc_loadXML(a){this.topNode=null;this.hasErrors=false;this.source=a;return this.parse()}
function _XMLDoc_parse(){var a=0;for(err=false;!err;){var b="",c=this.source.indexOf("<",a),e=1;if(c==-1)break;e=c;var f=this.source.substring(a,e);if(f.length!=0)err=!this.handleNode(new XMLNode("TEXT",this,f));if(c==this.source.indexOf("<?",a)){a=this.parsePI(this.source,a+2);if(a==0)err=true}else if(c==this.source.indexOf("<!DOCTYPE",a)){a=this.parseDTD(this.source,c+9);if(a==0)err=true}else{if(c==this.source.indexOf("<!--",a))b="--";if(c==this.source.indexOf("<![CDATA[",a))b="]]";c=this.source.indexOf(b+
">",c);if(c==-1)return this.error("expected closing tag sequence: "+b+">");a=c+b.length;f=this.source.substring(e+1,a);if(b=this.parseTag(f))err=!this.handleNode(b);a=a+1}}return!err}
function _XMLDoc_parseAttribute(a,b,c){for(;b<a.length&&whitespace.indexOf(a.charAt(b))!=-1;)b++;if(b>=a.length)return b;for(var e=b;b<a.length&&a.charAt(b)!="=";)b++;var f="attributes must have values";if(b>=a.length)return this.error(f);for(var g=trim(a.substring(e,b++),false,true);b<a.length&&whitespace.indexOf(a.charAt(b))!=-1;)b++;if(b>=a.length)return this.error(f);f="attribute values must be in quotes";var h=a.charAt(b++);if(quotes.indexOf(h)==-1)return this.error(f);for(e=b;b<a.length&&a.charAt(b)!=
h;)b++;if(b>=a.length)return this.error(f);if(!c.addAttribute(g,trim(a.substring(e,b++),false,true)))return 0;return b}function _XMLDoc_parseDTD(a,b){var c=a.indexOf(">",b);if(c==-1)return this.error("error in DTD: expected '>'");var e="",f=a.indexOf("[",b);if(f!=-1&&f<c)e="]";for(;;){c=a.indexOf(e+">",b);if(c==-1)return this.error("expected closing tag sequence: "+e+">");b=c+e.length+1;if(a.substring(c-1,c+2)!="]]\>")break}return b}function _XMLDoc_parsePI(a,b){return a.indexOf("?>",b)+2}
function _XMLDoc_parseTag(a){if(a.indexOf("!--")==0)return new XMLNode("COMMENT",this,a.substring(3,a.length-2));if(a.indexOf("![CDATA[")==0)return new XMLNode("CDATA",this,a.substring(8,a.length-2));var b=new XMLNode;b.doc=this;if(a.charAt(0)=="/"){b.nodeType="CLOSE";a=a.substring(1)}else b.nodeType="OPEN";if(a.charAt(a.length-1)=="/"){if(b.nodeType=="CLOSE")return this.error("singleton close tag");else b.nodeType="SINGLE";a=a.substring(0,a.length-1)}if(b.nodeType!="CLOSE")b.attributes=[];if(b.nodeType==
"OPEN")b.children=[];a=trim(a,true,true);if(a.length==0)return this.error("empty tag");var c=firstWhiteChar(a,0);if(c==-1){b.tagName=a;return b}b.tagName=a.substring(0,c);for(c=c;c<a.length;){c=this.parseAttribute(a,c,b);if(this.pos==0)return null}return b}function _XMLDoc_removeNodeFromTree(a){var b=this.getUnderlyingXMLText();a=a.getUnderlyingXMLText();var c=b.indexOf(a),e=b.substr(0,c);e+=b.substr(c+a.length);return new XMLDoc(e,this.errFn)}
function _XMLDoc_replaceNodeContents(a,b){b=this.createXMLNode("<X>"+b+"</X>");a.children=b.children;return this}
function _XMLDoc_selectNode(a){a=trim(a,true,true);var b,c,e,f,g;c=this.source?this.docNode:this;if(!a)return c;if(a.indexOf("/")==0)a=a.substr(1);a=a.replace(b,"");if(b=a.split("/")[0]){if(a.indexOf("/")==0)a=a.substr(1);a=a.replace(b,"");e=_XMLDoc_getTagNameParams(b,this);b=e[0];f=e[1];g=e[2];e=e[3];c=b=="*"?c.getElements():c.getElements(b);if(c.length)if(f<0){b=c;for(f=0;f<b.length;){if(c=g?b[f].getAttribute(g)!=e?false:true:true)if(c=b[f].selectNode(a))return c;f++}}else if(f<c.length)if(c=c[f].selectNode(a))return c}}
function _XMLDoc_selectNodeText(a){a=this.selectNode(a);return a!=null?a.getText():null}
function XMLNode(a,b,c){this.content=a=="TEXT"||a=="CDATA"||a=="COMMENT"?c:null;this.children=this.attributes=null;this.doc=b;this.nodeType=a;this.tagName=this.parent="";this.addAttribute=_XMLNode_addAttribute;this.addElement=_XMLNode_addElement;this.getAttribute=_XMLNode_getAttribute;this.getAttributeNames=_XMLNode_getAttributeNames;this.getElementById=_XMLNode_getElementById;this.getElements=_XMLNode_getElements;this.getText=_XMLNode_getText;this.getParent=_XMLNode_getParent;this.getUnderlyingXMLText=
_XMLNode_getUnderlyingXMLText;this.removeAttribute=_XMLNode_removeAttribute;this.selectNode=_XMLDoc_selectNode;this.selectNodeText=_XMLDoc_selectNodeText;this.toString=_XMLNode_toString}function _XMLNode_addAttribute(a,b){this.attributes["_"+a]=b;return true}function _XMLNode_addElement(a){a.parent=this;this.children[this.children.length]=a;return true}function _XMLNode_getAttribute(a){if(this.attributes==null)return null;return this.attributes["_"+a]}
function _XMLNode_getAttributeNames(){if(this.attributes==null)return[];var a=[];for(var b in this.attributes)if(typeof this.attributes[b]!=="function")a[a.length]=b.substring(1);return a}function _XMLNode_getElementById(a){var b=this,c;if(b.getAttribute("id")==a)return b;else{b=b.getElements();for(var e=0;e<b.length;){c=b[e].getElementById(a);if(c!=null)break;e++}}return c}
function _XMLNode_getElements(a){if(this.children==null)return[];for(var b=[],c=0;c<this.children.length;c++)if(this.children[c].nodeType=="ELEMENT"&&(a==null||this.children[c].tagName==a))b[b.length]=this.children[c];return b}function _XMLNode_getText(){if(this.nodeType=="ELEMENT"){if(this.children==null)return null;for(var a="",b=0;b<this.children.length;b++){var c=this.children[b].getText();a+=c==null?"":c}return a}else return this.nodeType=="TEXT"?convertEscapes(this.content):this.content}
function _XMLNode_getParent(){return this.parent}function _XMLNode_getUnderlyingXMLText(){var a="";return a=_displayElement(this,a)}
function _XMLNode_removeAttribute(a){if(a==null)return this.doc.error("You must pass an attribute name into the removeAttribute function");var b=this.getAttributeNames(),c=b.length,e=[];for(intLoop=0;intLoop<c;intLoop++)e[intLoop]=this.getAttribute(b[intLoop]);this.attributes=[];for(intLoop=0;intLoop<c;intLoop++)b[intLoop]!=a&&this.addAttribute(b[intLoop],e[intLoop]);return true}
function _XMLNode_toString(){return""+this.nodeType+":"+(this.nodeType=="TEXT"||this.nodeType=="CDATA"||this.nodeType=="COMMENT"?this.content:this.tagName)};function LASRequest(a){a||(a='<?xml version="1.0"?><lasRequest href="file:las.xml"><link match="/lasdata/operations/shade"/><args><link match="/lasdata/datasets/coads_climatology_cdf/variables/airt"></link><region><range type="x" low="-180.0" high="180.0"/><range type="y" low="-89.5" high="89.5"/><point type="t" v="15-Jan"/></region></args></lasRequest>');this.DOM=new XMLDoc(a,_LASReq_parseError);a=this.DOM.selectNode("/link");if(!this.DOM.selectNode("/properties")){var b=this.DOM.createXMLNode("<properties></properties>");
this.DOM=this.DOM.insertNodeAfter(a,b)}this.getOperation=LASReq_getOperation;this.setOperation=LASReq_setOperation;this.addPropertyGroup=LASReq_addPropertyGroup;this.removePropertyGroup=LASReq_removePropertyGroup;this.getProperty=LASReq_getProperty;this.setProperty=LASReq_setProperty;this.addProperty=LASReq_addProperty;this.removeProperty=LASReq_removeProperty;this.getVariable=LASReq_getVariable;this.setVariable=LASReq_setVariable;this.addVariable=LASReq_addVariable;this.removeVariable=LASReq_removeVariable;
this.removeVariables=LASReq_removeVariables;this.replaceVariable=LASReq_replaceVariable;this.getDataset=LASReq_getDataset;this.addTextConstraint=LASReq_addTextConstraint;this.addVariableConstraint=LASReq_addVariableConstraint;this.removeConstraints=LASReq_removeConstraints;this.getTextConstraints=LASReq_getTextConstraints;this.getVariableConstraints=LASReq_getVariableConstraints;this.setAnalysis=LASReq_setAnalysis;this.getAnalysis=LASReq_getAnalysis;this.removeAnalysis=LASReq_removeAnalysis;this.addRegion=
LASReq_addRegion;this.removeRegion=LASReq_removeRegion;this.getRangeLo=LASReq_getRangeLo;this.getRangeHi=LASReq_getRangeHi;this.getAxisType=LASReq_getAxisType;this.setRange=LASReq_setRange;this.addRange=LASReq_addRange;this.removeRange=LASReq_removeRange;this.getXMLText=LASReq_getXMLText;this.getVariableNode=LASReq_getVariableNode;this.getVariableNodeByIndex=LASReq_getVariableNodeByIndex}
function LASReq_getOperation(a){var b=this.DOM.selectNode("/link");b=(new String(b.getAttribute("match"))).split("/");var c="";if(a=="LAS6")c=b[3];else(c=(new String(b[3])).split("'")[1])||(c=this.getOperation("LAS6"));return c}function LASReq_setOperation(a,b){var c="";c=b=="LAS6"?"/lasdata/operations/"+a:"/lasdata/operations/operation[@ID='"+a+"']";a=this.DOM.selectNode("/link");a.removeAttribute("match");a.addAttribute("match",c)}
function LASReq_addPropertyGroup(a){if(!this.DOM.selectNode("/properties")){var b=this.DOM.createXMLNode("<properties></properties>");this.DOM=this.DOM.insertNodeAfter(operationNode,b)}var c=this.DOM.selectNode("/properties");if(!this.DOM.selectNode("/properties/"+a)){b=this.DOM.createXMLNode("<"+a+"></"+a+">");this.DOM=this.DOM.insertNodeInto(c,b)}}function LASReq_removePropertyGroup(a){if(a=this.DOM.selectNode("/properties/"+a))this.DOM=this.DOM.removeNodeFromTree(a)}
function LASReq_getProperty(a,b){a="/properties/"+a+"/"+b;return this.DOM.selectNode(a)?this.DOM.selectNodeText(a):null}function LASReq_setProperty(a,b,c){var e=this.DOM.selectNode("/properties/"+a+"/"+b);if(e)this.DOM=this.DOM.replaceNodeContents(e,c);else this.addProperty(a,b,c)}
function LASReq_addProperty(a,b,c){var e="/properties/"+a;(e=this.DOM.selectNode(e))||this.addPropertyGroup(a);if(this.DOM.selectNode("/properties/"+a+"/"+b))this.setProperty(a,b,c);else{e="/properties/"+a;e=this.DOM.selectNode(e);a=this.DOM.createXMLNode("<"+b+">"+c+"</"+b+">");this.DOM=this.DOM.insertNodeInto(e,a)}}function LASReq_removeProperty(a,b){if(a=this.DOM.selectNode("/properties/"+a+"/"+b))this.DOM=this.DOM.removeNodeFromTree(a)}
function LASReq_getDataset(a){a=this.DOM.selectNode("/args/link["+(a?a:0)+"]");matchString=new String(a.getAttribute("match"));return matchString.split("/")[3]}function LASReq_getVariable(a){if(a=this.DOM.selectNode("/args/link["+(a?a:0)+"]")){matchString=new String(a.getAttribute("match"));return matchString.split("/")[5]}}function LASReq_setVariable(a,b){this.removeVariables();this.addVariable(a,b)}
function LASReq_addVariable(a,b){a=this.DOM.createXMLNode('<link match="/lasdata/datasets/'+a+"/variables/"+b+'"></link>');b=this.DOM.selectNode("/args");var c=b.getElements();this.DOM=c.length==0?this.DOM.insertNodeInto(b,a):this.DOM.insertNodeAfter(c[c.length-1],a)}
function LASReq_OLD_removeVariable(a,b){a=this.DOM.selectNode("/args").getElements("link");for(i=0;i<a.length;i++){matchString=new String(a[i].getAttribute("match"));if(matchString.split("/")[5]==b)this.DOM=this.DOM.removeNodeFromTree(a[i])}}function LASReq_removeVariable(a){a=a?a:0;var b=this.DOM.selectNode("/args").getElements("link");if(b.length>a)this.DOM=this.DOM.removeNodeFromTree(b[a])}
function LASReq_removeVariables(){var a=this.DOM.selectNode("/args").getElements("link");for(i=0;i<a.length;i++)this.DOM=this.DOM.removeNodeFromTree(a[i])}function LASReq_replaceVariable(a,b,c){a=this.DOM.createXMLNode('<link match="/lasdata/datasets/'+a+"/variables/"+b+'"></link>');c=this.DOM.selectNode("/args/link["+(c?c:0)+"]");this.DOM=this.DOM.insertNodeAfter(c,a);this.DOM=this.DOM.removeNodeFromTree(c)}
function LASReq_addTextConstraint(a,b,c,e){var f=this.DOM.selectNode("/args");a=this.DOM.createXMLNode('<constraint id="'+e+'"type="text"><v>'+a+"</v><v>"+b+"</v><v>"+c+"</v></constraint>");this.DOM=this.DOM.insertNodeInto(f,a)}
function LASReq_getTextConstraints(){var a=[],b=this.DOM.selectNode("/args").getElements("constraint"),c=0;for(i=0;i<b.length;i++){constraintType=new String(b[i].getAttribute("type"));var e=b[i].getAttribute("id")?b[i].getAttribute("id"):"";if(constraintType=="text"){var f=b[i].getElements("v");tc={name:f[0].getText(),op:f[1].getText(),value:f[2].getText(),id:e};a[c++]=tc}}return a}
function LASReq_getVariableConstraints(){var a=[],b=this.DOM.selectNode("/args").getElements("constraint"),c=0;for(i=0;i<b.length;i++){constraintType=new String(b[i].getAttribute("type"));var e=b[i].getAttribute("id")?b[i].getAttribute("id"):"";if(constraintType=="variable"){var f=b[i].getElements("link"),g=(new String(f[0].getAttribute("match"))).split("/");f=g[3];g=g[5];var h=b[i].getAttribute("op"),j=b[i].getElements("v")[0].getText();vc={dsID:f,varID:g,op:h,value:j,id:e};a[c++]=vc}}return a}
function LASReq_addVariableConstraint(a,b,c,e,f){var g=this.DOM.selectNode("/args");a=this.DOM.createXMLNode('<constraint id="'+f+'" type="variable" op="'+c+'">'+('<link match="/lasdata/datasets/'+a+"/variables/"+b+'"/>')+"<v>"+e+"</v></constraint>");this.DOM=this.DOM.insertNodeInto(g,a)}function LASReq_removeConstraints(){var a=this.DOM.selectNode("/args").getElements("constraint");for(i=0;i<a.length;i++)this.DOM=this.DOM.removeNodeFromTree(a[i])}
function LASReq_getAnalysis(a){var b=null;if(b=this.getVariableNodeByIndex(a))if(a=b.getElements("analysis")[0]){b={};b.axis=[];b.label=String(a.getAttribute("label"));a=a.getElements("axis");for(i=0;i<a.length;i++)b.axis.push({type:String(a[i].getAttribute("type")),lo:String(a[i].getAttribute("lo")),hi:String(a[i].getAttribute("hi")),op:String(a[i].getAttribute("op"))})}else b=null;else b=null;return b}
function LASReq_setAnalysis(a,b){a=this.getVariableNodeByIndex(a);var c='<analysis label="'+b.label+'"></analysis>',e=this.DOM.createXMLNode(c);for(i=0;i<b.axis.length;i++){c='<axis type="'+b.axis[i].type+'" lo="'+b.axis[i].lo+'" hi="'+b.axis[i].hi+'" op="'+b.axis[i].op+'"/>';c=this.DOM.createXMLNode(c);e.addElement(c)}this.DOM=this.DOM.insertNodeInto(a,e)}
function LASReq_removeAnalysis(a){a=this.getVariableNodeByIndex(a).getElements("analysis");for(i=0;i<a.length;i++)this.DOM=this.DOM.removeNodeFromTree(a[i])}function LASReq_addRegion(){var a=this.DOM.createXMLNode("<region></region>"),b=this.DOM.selectNode("/args"),c=b.getElements();this.DOM=c.length==0?this.DOM.insertNodeInto(b,a):this.DOM.insertNodeAfter(c[c.length-1],a)}
function LASReq_removeRegion(a){a=a?a:0;var b=this.DOM.selectNode("/args").getElements("region");if(b.length>a)this.DOM=this.DOM.removeNodeFromTree(b[a])}function LASReq_getRangeLo(a,b){var c=null;c=this.getAxisType(a,b);if(c=="range"){b=b?b:0;a=this.DOM.selectNode("/args/region["+b+']/range[@type="'+a+'"]');c=a.getAttribute("low")}else if(c=="point"){b=b?b:0;a=this.DOM.selectNode("/args/region["+b+']/point[@type="'+a+'"]');c=a.getAttribute("v")}else c=null;return c}
function LASReq_getRangeHi(a,b){var c=null;return c=this.getAxisType(a,b)=="range"?this.DOM.selectNode("/args/region["+(b?b:0)+']/range[@type="'+a+'"]').getAttribute("high"):null}function LASReq_getAxisType(a,b){var c=null;b=b?b:0;var e=this.DOM.selectNode("/args/region["+b+']/range[@type="'+a+'"]');if(e)c="range";else if(e=this.DOM.selectNode("/args/region["+b+']/point[@type="'+a+'"]'))c="point";return c}function LASReq_setRange(a,b,c,e){this.removeRange(a,e);this.addRange(a,b,c,e)}
function LASReq_addRange(a,b,c,e){e=e?e:0;var f=this.DOM.selectNode("/args/region["+e+"]");f||this.addRegion();f="";f=c!=null&&c!=b?'<range type="'+a+'" low="'+b+'" high="'+c+'"/>':'<point type="'+a+'" v="'+b+'"/>';a=this.DOM.createXMLNode(f);f=this.DOM.selectNode("/args/region["+e+"]");this.DOM=this.DOM.insertNodeInto(f,a)}
function LASReq_removeRange(a,b){b=b?b:0;if(this.DOM.selectNode("/args/region["+b+"]")){var c=this.DOM.selectNode("/args/region["+b+']/range[@type="'+a+'"]');if(c)this.DOM=this.DOM.removeNodeFromTree(c);else if(c=this.DOM.selectNode("/args/region["+b+']/point[@type="'+a+'"]'))this.DOM=this.DOM.removeNodeFromTree(c)}}function LASReq_getXMLText(){return this.DOM.getUnderlyingXMLText()}
function LASReq_getVariableNode(a,b){a=this.DOM.selectNode("/args").getElements("link");for(i=0;i<a.length;i++){matchString=new String(a[i].getAttribute("match"));if(matchString.split("/")[5]==b)return a[i]}}function LASReq_getVariableNodeByIndex(a){var b=this.DOM.selectNode("/args").getElements("link");return b[a]?b[a]:null}function _LASReq_parseError(a){alert(a)};function DateWidget(a,b,c,e,f,g){this.setCallback=DateWidget_setCallback;this.render=DateWidget_render;this.renderToNode=DateWidget_renderToNode;this.disable=DateWidget_disable;this.enable=DateWidget_enable;this.show=DateWidget_show;this.hide=DateWidget_hide;this.getValue=DateWidget_getValue;this.setValue=DateWidget_setValue;this.initializeYearMenu=DateWidget_initializeYearMenu;this.setDateRange=DateWidget_setDateRange;this.setDate1=DateWidget_setDate1;this.setDate2=DateWidget_setDate2;this.resetDateRange=
DateWidget_resetDateRange;this.resetDate1=DateWidget_resetDate1;this.resetDate2=DateWidget_resetDate2;this.toString=DateWidget_toString;this.getDateLo=DateWidget_getDateLo;this.getDateHi=DateWidget_getDateHi;this.getDate1=DateWidget_getDate1;this.getDate2=DateWidget_getDate2;this.alert=DateWidget_alert;this.setDeltaMinutes=DateWidget_setDeltaMinutes;this.setOffsetMinutes=DateWidget_setOffsetMinutes;this.getDate1_Ferret=DateWidget_getDate1_Ferret;this.getDate2_Ferret=DateWidget_getDate2_Ferret;this.parseDate=
DateWidget_parseDate;this.febDays=DateWidget_febDays;this.twoDigit=DateWidget_twoDigit;this.fourDigit=DateWidget_fourDigit;this.correctOrder=DateWidget_correctOrder;this.addEvent=DateWidget_addEvent;this.flash=DateWidget_flash;this.selectYear=DateWidget_selectYear;this.selectMonth=DateWidget_selectMonth;this.selectDay=DateWidget_selectDay;this.selectTime=DateWidget_selectTime;this.selectChange=DateWidget_selectChange;this.widgetType="DateWidget";this.visible=this.disabled=this.climatology=0;this.deltaMinutes=
c?c:1440;this.offsetMinutes=e?e:0;var h,j;try{h=this.parseDate(a,f)}catch(k){a='DateWidget ERROR: new:  error parsing "'+a+'"\n'+k;alert(a)}try{j=this.parseDate(b,g)}catch(n){a='DateWidget ERROR: new:  error parsing "'+b+'"\n'+n;alert(a)}this.yearLo=h[0];this.monthLo=h[1];this.dayLo=h[2];this.hourLo=h[3];this.minuteLo=h[4];this.secondLo=h[5];this.yearHi=j[0];this.monthHi=j[1];this.dayHi=j[2];this.hourHi=j[3];this.minuteHi=j[4];this.secondHi=j[5];this.year1=this.yearLo;this.month1=this.monthLo;this.day1=
this.dayLo;this.hour1=this.hourLo;this.minute1=this.minuteLo;this.second1=this.secondLo;this.year2=this.yearHi;this.month2=this.monthHi;this.day2=this.dayHi;this.hour2=this.hourHi;this.minute2=this.minuteHi;this.second2=this.secondHi}
function DateWidget_renderToNode(a,b,c){this.node=a;this.menu_set_1=b;this.menu_set_2=c;for(var e=a.childNodes?a.childNodes:[],f=e.length-1;f>=0;f--){var g=e[f];g&&a.removeChild(g)}var h,j,k,n,m,o,p,q,r=f=0;if(!b){error_msg='DateWidget ERROR:  render: menu_set_1 must be defined and  must contain only characters from "YMDT"';throw error_msg;}e=document.createElement("select");e.setAttribute("id","DW_Year1");e.widget=this;this.Year1=e;if(b.indexOf("Y")<0){this.Year1.style.display="none";this.climatology=
f=1;text1=document.createTextNode("Climatology:  ");h=document.createElement("span");h.setAttribute("id","DW_Text1");h.appendChild(text1);h.widget=this;this.Text1=h}g=document.createElement("select");g.setAttribute("id","DW_Month1");g.widget=this;this.Month1=g;if(b.indexOf("M")<0)this.Month1.style.display="none";j=document.createElement("select");j.setAttribute("id","DW_Day1");j.widget=this;this.Day1=j;if(b.indexOf("D")<0)this.Day1.style.display="none";k=document.createElement("select");k.setAttribute("id",
"DW_Time1");k.widget=this;this.Time1=k;if(b.indexOf("T")<0)this.Time1.style.display="none";if(c){m=document.createElement("select");m.setAttribute("id","DW_Year2");m.widget=this;this.Year2=m;if(c.indexOf("Y")<0){this.Year2.style.display="none";r=1;text2=document.createTextNode("Climatology:  ");n=document.createElement("span");n.setAttribute("id","DW_Text2");n.appendChild(text2);n.widget=this;this.Text2=n}o=document.createElement("select");o.setAttribute("id","DW_Month2");o.widget=this;this.Month2=
o;if(c.indexOf("M")<0)this.Month2.style.display="none";p=document.createElement("select");p.setAttribute("id","DW_Day2");p.widget=this;this.Day2=p;if(c.indexOf("D")<0)this.Day2.style.display="none";q=document.createElement("select");q.setAttribute("id","DW_Time2");q.widget=this;this.Time2=q;if(c.indexOf("T")<0)this.Time2.style.display="none";if(f!=r){error_msg='DateWidget ERROR:  render: menu_set_1 "'+b+'" and menu_set_2 "'+c+'" must both include or both exclude the "Y" flag in the menu_set';throw error_msg;
}}var l;r=document.createElement("table");r.setAttribute("id","DW_table");DW_tbody=document.createElement("tbody");DW_tbody.setAttribute("id","DW_tbody");f=document.createElement("tr");f.setAttribute("id","DW_tr1");l=document.createElement("td");l.setAttribute("id","DW_td1");r.appendChild(DW_tbody);DW_tbody.appendChild(f);f.appendChild(l);if(e.style.display=="none"){l.appendChild(e);l.appendChild(h)}g.style.display=="none"&&l.appendChild(g);j.style.display=="none"&&l.appendChild(j);k.style.display==
"none"&&l.appendChild(k);for(f=0;f<b.length;f++)switch(b.charAt(f)){case "Y":l.appendChild(e);break;case "M":l.appendChild(g);break;case "D":l.appendChild(j);break;case "T":l.appendChild(k);break;default:error_msg='DateWidget ERROR:  render: menu_set "'+b+'" must contain only characters from "YMDT"';throw error_msg;}if(c){h=document.createElement("tr");h.setAttribute("id","DW_tr2");b=document.createElement("td");b.setAttribute("id","DW_td2");DW_tbody.appendChild(h);h.appendChild(b);if(m.style.display==
"none"){b.appendChild(m);b.appendChild(n)}o.style.display=="none"&&b.appendChild(o);p.style.display=="none"&&b.appendChild(p);q.style.display=="none"&&b.appendChild(q);for(f=0;f<c.length;f++)switch(c.charAt(f)){case "Y":b.appendChild(m);break;case "M":b.appendChild(o);break;case "D":b.appendChild(p);break;case "T":b.appendChild(q);break;default:error_msg='DateWidget ERROR:  render: menu_set "'+c+'" must contain only characters from "YMDT"';throw error_msg;}}a.appendChild(r);this.initializeYearMenu(e);
c&&this.initializeYearMenu(m);this.visible=1}
function DateWidget_render(a,b,c){this.element_id=a;this.menu_set_1=b;this.menu_set_2=c;a=document.getElementById(this.element_id);for(var e=a.childNodes?a.childNodes:[],f=e.length-1;f>=0;f--){var g=e[f];g&&a.removeChild(g)}var h,j,k,n,m,o,p,q,r=f=0;if(!b){error_msg='DateWidget ERROR:  render: menu_set_1 must be defined and  must contain only characters from "YMDT"';throw error_msg;}e=document.createElement("select");e.setAttribute("id","DW_Year1");e.widget=this;this.Year1=e;if(b.indexOf("Y")<0){this.Year1.style.display=
"none";this.climatology=f=1;text1=document.createTextNode("Climatology:  ");h=document.createElement("span");h.setAttribute("id","DW_Text1");h.appendChild(text1);h.widget=this;this.Text1=h}g=document.createElement("select");g.setAttribute("id","DW_Month1");g.widget=this;this.Month1=g;if(b.indexOf("M")<0)this.Month1.style.display="none";j=document.createElement("select");j.setAttribute("id","DW_Day1");j.widget=this;this.Day1=j;if(b.indexOf("D")<0)this.Day1.style.display="none";k=document.createElement("select");
k.setAttribute("id","DW_Time1");k.widget=this;this.Time1=k;if(b.indexOf("T")<0)this.Time1.style.display="none";if(c){m=document.createElement("select");m.setAttribute("id","DW_Year2");m.widget=this;this.Year2=m;if(c.indexOf("Y")<0){this.Year2.style.display="none";r=1;text2=document.createTextNode("Climatology:  ");n=document.createElement("span");n.setAttribute("id","DW_Text2");n.appendChild(text2);n.widget=this;this.Text2=n}o=document.createElement("select");o.setAttribute("id","DW_Month2");o.widget=
this;this.Month2=o;if(c.indexOf("M")<0)this.Month2.style.display="none";p=document.createElement("select");p.setAttribute("id","DW_Day2");p.widget=this;this.Day2=p;if(c.indexOf("D")<0)this.Day2.style.display="none";q=document.createElement("select");q.setAttribute("id","DW_Time2");q.widget=this;this.Time2=q;if(c.indexOf("T")<0)this.Time2.style.display="none";if(f!=r){error_msg='DateWidget ERROR:  render: menu_set_1 "'+b+'" and menu_set_2 "'+c+'" must both include or both exclude the "Y" flag in the menu_set';
throw error_msg;}}var l;r=document.createElement("table");r.setAttribute("id","DW_table");DW_tbody=document.createElement("tbody");DW_tbody.setAttribute("id","DW_tbody");f=document.createElement("tr");f.setAttribute("id","DW_tr1");l=document.createElement("td");l.setAttribute("id","DW_td1");r.appendChild(DW_tbody);DW_tbody.appendChild(f);f.appendChild(l);if(e.style.display=="none"){l.appendChild(e);l.appendChild(h)}g.style.display=="none"&&l.appendChild(g);j.style.display=="none"&&l.appendChild(j);
k.style.display=="none"&&l.appendChild(k);for(f=0;f<b.length;f++)switch(b.charAt(f)){case "Y":l.appendChild(e);break;case "M":l.appendChild(g);break;case "D":l.appendChild(j);break;case "T":l.appendChild(k);break;default:error_msg='DateWidget ERROR:  render: menu_set "'+b+'" must contain only characters from "YMDT"';throw error_msg;}if(c){h=document.createElement("tr");h.setAttribute("id","DW_tr2");b=document.createElement("td");b.setAttribute("id","DW_td2");DW_tbody.appendChild(h);h.appendChild(b);
if(m.style.display=="none"){b.appendChild(m);b.appendChild(n)}o.style.display=="none"&&b.appendChild(o);p.style.display=="none"&&b.appendChild(p);q.style.display=="none"&&b.appendChild(q);for(f=0;f<c.length;f++)switch(c.charAt(f)){case "Y":b.appendChild(m);break;case "M":b.appendChild(o);break;case "D":b.appendChild(p);break;case "T":b.appendChild(q);break;default:error_msg='DateWidget ERROR:  render: menu_set "'+c+'" must contain only characters from "YMDT"';throw error_msg;}}a.appendChild(r);this.initializeYearMenu(e);
c&&this.initializeYearMenu(m);this.visible=1}
function DateWidget_initializeYearMenu(a){var b,c,e;if(a.getAttribute("id")=="DW_Year1"){b=this.yearLo;c=this.yearHi;if(this.year1>this.year2){e=this.year2;this.flash(a)}else e=this.year1}else{b=this.yearLo;c=this.yearHi;if(this.year1>this.year2){e=this.year1;this.flash(a)}else e=this.year2}c=c-b+1;var f=b;with(a){for(i=options.length=0;i<c;i++){options[i]=new Option(f,f);f++}if(this.initializing){this.internallyForced=1;if(name=="Year1")options[0].selected=true;else options[length-1].selected=true;
this.initializing=0}else{f=b;for(i=0;i<c;i++){if(f==e)options[i].selected=true;f++}}}a.onchange=this.selectChange;this.selectYear(a)}function DateWidget_setDateRange(a,b,c,e){this.resetDateRange();this.setDate1(a,c);this.setDate2(b,e)}function DateWidget_setDate1(a,b){a=this.parseDate(a,b);this.year1=a[0];this.month1=a[1];this.day1=a[2];this.hour1=a[3];this.minute1=a[4];this.second1=a[5];if(this.climatology)this.Month1&&this.selectMonth(this.Month1);else this.initializeYearMenu(this.Year1)}
function DateWidget_setDate2(a,b){a=this.parseDate(a,b);this.year2=a[0];this.month2=a[1];this.day2=a[2];this.hour2=a[3];this.minute2=a[4];this.second2=a[5];if(this.Year2)this.initializeYearMenu(this.Year2);else this.Month2&&this.selectMonth(this.Month2)}
function DateWidget_toString(){return"dateLo = "+this.getDateLo()+"\ndateHi = "+this.getDateHi()+"\ndate1 = "+this.getDate1()+"\ndate2 = "+this.getDate2()+"\nthis.deltaMinutes = "+this.deltaMinutes+"\nthis.offsetMinutes = "+this.offsetMinutes+"\n"}
function DateWidget_getDateLo(){var a=this.monthLo=="00"?"":"-"+this.monthLo,b=this.dayLo=="00"?"":"-"+this.dayLo,c=this.Time1?" "+this.twoDigit(this.hourLo)+":"+this.twoDigit(this.minuteLo)+":"+this.twoDigit(this.secondLo):"";return this.fourDigit(this.yearLo)+a+b+c}
function DateWidget_getDateHi(){var a=this.monthHi=="00"?"":"-"+this.monthHi,b=this.dayHi=="00"?"":"-"+this.dayHi,c=this.Time2?" "+this.twoDigit(this.hourHi)+":"+this.twoDigit(this.minuteHi)+":"+this.twoDigit(this.secondHi):"";return this.fourDigit(this.yearHi)+a+b+c}
function DateWidget_getDate1(){var a=this.month1=="00"?"":"-"+this.month1,b=this.day1=="00"?"":"-"+this.day1,c=this.Time1?" "+this.twoDigit(this.hour1)+":"+this.twoDigit(this.minute1)+":"+this.twoDigit(this.second1):"";return this.fourDigit(this.year1)+a+b+c}
function DateWidget_getDate2(){var a=this.month2=="00"?"":"-"+this.month2,b=this.day2=="00"?"":"-"+this.day2,c=this.Time2?" "+this.twoDigit(this.hour2)+":"+this.twoDigit(this.minute2)+":"+this.twoDigit(this.second2):"";return this.Year2?this.fourDigit(this.year2)+a+b+c:""}
function DateWidget_getDate1_Ferret(){var a=new Array("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec");a=this.month1=="00"?"":"-"+a[Number(this.month1)-1];var b=this.day1=="00"?"":this.day1,c=this.menu_set_1.indexOf("T")!=-1?this.Time1?" "+this.twoDigit(this.hour1)+":"+this.twoDigit(this.minute1)+":"+this.twoDigit(this.second1):"":"";return b+a+"-"+this.fourDigit(this.year1)+c}
function DateWidget_getDate2_Ferret(){var a=new Array("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec");a=this.month2=="00"?"":"-"+a[Number(this.month2)-1];var b=this.day2=="00"?"":this.day2,c=this.menu_set_2.indexOf("T")!=-1?this.Time2?" "+this.twoDigit(this.hour2)+":"+this.twoDigit(this.minute2)+":"+this.twoDigit(this.second2):"":"";return b+a+"-"+this.fourDigit(this.year2)+c}
function DateWidget_getValue(){var a=this.getDate1_Ferret();if(this.menu_set_2)a=a+","+this.getDate2_Ferret();return a}function DateWidget_setValue(a,b){b=b?b:1;b==1?this.setDate1(a):this.setDate2(a)}function DateWidget_alert(){alert(this.toString())}function DateWidget_resetDate1(){this.setDate1(this.getDateLo())}function DateWidget_resetDate2(){this.setDate2(this.getDateHi())}function DateWidget_resetDateRange(){this.resetDate1();this.resetDate2()}
function DateWidget_setDeltaMinutes(a){this.deltaMinutes=a}function DateWidget_setOffsetMinutes(a){this.offsetMinutes=a}function DateWidget_disable(a){for(var b=document.getElementById(this.element_id).getElementsByTagName("select"),c=0;c<b.length;c++)switch(a){case "hi":if(b[c].id[b[c].id.length-1]=="2")b[c].disabled=1;else break;case "lo":if(b[c].id[b[c].id.length-1]=="1")b[c].disabled=1;break;default:b[c].disabled=1}this.disabled=1}
function DateWidget_enable(a){for(var b=document.getElementById(this.element_id).getElementsByTagName("select"),c=0;c<b.length;c++)switch(a){case "hi":if(b[c].id[b[c].id.length-1]=="2")b[c].disabled=0;else break;case "lo":if(b[c].id[b[c].id.length-1]=="1")b[c].disabled=0;break;default:b[c].disabled=0}this.disabled=0}function DateWidget_show(){document.getElementById(this.element_id).style.visibility="visible";this.visible=1}
function DateWidget_hide(){document.getElementById(this.element_id).style.visibility="hidden";this.visible=0}function DateWidget_setCallback(a){this.callback=a}
function DateWidget_parseDate(a,b){var c,e=new Date;c=new Date;switch(a){case "NOW":break;case "TODAY":c=new Date;e=new Date(c.getFullYear(),c.getMonth(),c.getDate(),0,0,0);c=new Date(c.getFullYear(),c.getMonth(),c.getDate(),0,0,0);break;default:e=String(a).split(" ");var f=String(e[0]).split("-");c=String(e[0]).split("-");if(String(f[1]).length==3){var g={jan:"01",feb:"02",mar:"03",apr:"04",may:"05",jun:"06",jul:"07",aug:"08",sep:"09",oct:"10",nov:"11",dec:"12"}[String(f[1].toLowerCase())];c[0]=
f[2]?f[2]:"0001";c[1]=g;c[2]=f[0]}if(c[0]){if(Number(c[0]).valueOf()>=8E3){b='The DateWidget cannot handle years >= 8000.  Incoming date is "'+a+'"';throw b;}a=Number(c[0]).valueOf();if(a<100){a+=8E3;c[0]=String(a)}a=Number(c[0]);(new Date(a,1,1)).getFullYear()}if(e[1]){a=String(e[1]).split(":");c[3]=a[0];c[4]=a[1];c[5]=a[2]}else{c[3]="00";c[4]="00";c[5]="00"}if(Number(c[1]).valueOf()<1||Number(c[1]).valueOf()>12){b='DateWidget ERROR:  parseDate:  month "'+c[1]+'" must be in the range 1:12';throw b;
}if(Number(c[2]).valueOf()<1||Number(c[2]).valueOf()>31){b='DateWidget ERROR:  parseDate:  day "'+c[2]+'" must be in the range 1:31';throw b;}if(Number(c[3]).valueOf()<0||Number(c[3]).valueOf()>23){b='DateWidget ERROR:  parseDate:  hour "'+c[3]+'" must be in the range 0:23';throw b;}if(Number(c[4]).valueOf()<0||Number(c[4]).valueOf()>59){b='DateWidget ERROR:  parseDate:  minute "'+c[4]+'" must be in the range 0:59';throw b;}if(Number(c[5]).valueOf()<0||Number(c[5]).valueOf()>59){b='DateWidget ERROR:  parseDate:  second "'+
c[5]+'" must be in the range 0:59';throw b;}e=new Date(c[0],c[1]-1,c[2],c[3],c[4],c[5]);c=new Date(c[0],c[1]-1,c[2],c[3],c[4],c[5]);break}if(b){b=e.valueOf()+6E4*b;c=new Date(b)}with(c)c=new Array(getFullYear(),getMonth()+1,getDate(),getHours(),getMinutes(),getSeconds());c[5]=0;if(c[0]>=8E3)c[0]-=8E3;return c}function DateWidget_febDays(a){var b=28;if(a%4==0){b=29;if(a%100==0){b=28;if(a%400==0)b=29}}return b}function DateWidget_twoDigit(a){if(String(a).length==1)a="0"+String(a);return a}
function DateWidget_fourDigit(a){for(;String(a).length<4;)a="0"+String(a);return a}function DateWidget_correctOrder(){var a=1;if(this.year1>this.year2)a=0;else if(this.year1==this.year2)if(this.month1>this.month2)a=0;else if(this.month1==this.month2)if(this.day1>this.day2)a=0;else if(this.day1==this.day2)if(this.hour1>this.hour2)a=0;return a}
function DateWidget_addEvent(a,b,c,e){if(a.addEventListener){a.addEventListener(b,c,e);return true}else if(a.attachEvent)return a.attachEvent("on"+b,c);else a["on"+b]=c}function DateWidget_flash(a){var b="document.getElementById('"+a.id+"').style.backgroundColor = '#fff'";a.style.backgroundColor="#fcc";window.setTimeout(b,750)}
function DateWidget_selectYear(a){var b=new Array("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"),c=new Array("01","02","03","04","05","06","07","08","09","10","11","12");currentYear=a.options[a.selectedIndex].value;var e,f;if(a.getAttribute("id")=="DW_Year1"){f=this.Month1;this.year1=currentYear;if(this.year1==this.year2&&this.month1>this.month2){e=this.month2-1;this.flash(f)}else e=this.month1-1}else{f=this.Month2;this.year2=currentYear;if(this.year1==this.year2&&this.month1>
this.month2){e=this.month1-1;this.flash(f)}else e=this.month2-1}var g=0,h=11;a=a.getAttribute("id")=="DW_Year1"?this.Year2:this.Year1;if(currentYear==this.yearLo)g=this.monthLo-1;if(currentYear==this.yearHi)h=this.monthHi-1;if(f){with(f){a=h-g;var j=g;options.length=0;if(this.monthLo!="00"){for(k=0;k<=a;k++){options[k]=new Option(b[j],c[j]);j++}if(e<g||e>h)if(e<g)options[0].selected=true;else{var k=h-g;if(options[k])options[k].selected=true}else{k=e-g;if(options[k])options[k].selected=true}}}f.onchange=
this.selectChange;this.selectMonth(f)}else if(this.internallyForced)this.internallyForced=0;else if(a)if(!this.correctOrder()){this.internallyForced=1;this.initializeYearMenu(a)}}
function DateWidget_selectMonth(a){var b,c,e,f,g,h=new Array("01","02","03","04","05","06","07","08","09","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31");c=this.monthLo=="00"?"00":a.options[a.selectedIndex].value;if(a.getAttribute("id")=="DW_Month1"){g=this.Year2;f=this.Day1;b=this.year1;this.month1=c;if(this.year1==this.year2&&this.month1==this.month2&&this.day1>this.day2){e=this.day2;this.flash(f)}else e=this.day1}else{g=this.Year1;
f=this.Day2;b=this.year2;this.month2=c;if(this.year1==this.year2&&this.month1==this.month2&&this.day1>this.day2){e=this.day1;this.flash(f)}else e=this.day2}var j=1,k=31;switch(c){case "02":k=this.febDays(b);break;case "04":k=30;break;case "06":k=30;break;case "09":k=30;break;case "11":k=30;break;default:k=31;break}a.getAttribute("id");if(b==this.yearLo&&c==this.monthLo)j=this.dayLo;if(b==this.yearHi&&c==this.monthHi)k=this.dayHi;if(f){with(f){a=k-j+1;b=j-1;options.length=0;if(this.dayLo!="00"){for(c=
0;c<a;c++){options[c]=new Option(h[b],h[b]);b++}if(e<j||e>k){if(e<j)options[0].selected=true;else{c=k-j;options[c].selected=true}this.flash(f)}else{c=e-j;options[c].selected=true}}}f.onchange=this.selectChange;this.selectDay(f)}else if(this.internallyForced)this.internallyForced=0;else if(g)if(!this.correctOrder()){this.internallyForced=1;this.initializeYearMenu(g)}}
function DateWidget_selectDay(a){var b,c,e,f;e=this.dayLo=="00"?"00":a.options[a.selectedIndex].value;if(a.getAttribute("id")=="DW_Day1"){this.day1=e;a=this.Time1;f=this.Year2;b=this.year1;c=this.month1;e=this.day1;currentTime=this.hour1+":"+this.minute1}else{this.day2=e;a=this.Time2;f=this.Year1;b=this.year2;c=this.month2;e=this.day2;currentTime=this.hour2+":"+this.minute2}var g=this.offsetMinutes,h=1440;if(b==this.yearLo&&c==this.monthLo&&e==this.dayLo)g=Number(this.minuteLo)+Number(this.hourLo)*
60;if(b==this.yearHi&&c==this.monthHi&&e==this.dayHi)h=Number(this.minuteHi)+Number(this.hourHi)*60;if(a){with(a){var j="00:00";e=Math.floor(g/60);b=g-e*60;c=g;g=Math.floor((h-g)/this.deltaMinutes)+1;for(i=0;i<g;i++){j=this.twoDigit(e)+":"+this.twoDigit(b);options[i]=new Option(j,j);h=String(currentTime).split(":");if(h[0]==e&&h[1]==b)options[i].selected=true;c=Number(c)+Number(this.deltaMinutes);e=Math.floor(c/60);b=c-e*60;if(e>=24)break}}a.onchange=this.selectChange}if(this.internallyForced)this.internallyForced=
0;else if(f)if(!this.correctOrder()){this.internallyForced=1;this.initializeYearMenu(f)}}function DateWidget_selectTime(a){var b=String(a.options[a.selectedIndex].value).split(":");if(a.getAttribute("id")=="DW_Time1"){this.hour1=b[0];this.minute1=b[1]}else{this.hour2=b[0];this.minute2=b[1]}}
function DateWidget_selectChange(a){if(window.event&&window.event.srcElement)a=window.event.srcElement;else if(a&&a.target)a=a.target;else{alert("DateWidget ERROR:\n> selectChange:  This browser does not support standard javascript events.");return}if(a.nodeName.toLowerCase()!="select")alert("DateWidget ERROR:\n> selectChange:  event target ["+a.nodeName.toLowerCase()+"] should instead be [select]");else{a=a;var b=a.widget;switch(a.getAttribute("id")){case "DW_Year1":b.selectYear(a);break;case "DW_Month1":b.selectMonth(a);
break;case "DW_Day1":b.selectDay(a);break;case "DW_Time1":b.selectTime(a);break;case "DW_Year2":b.selectYear(a);break;case "DW_Month2":b.selectMonth(a);break;case "DW_Day2":b.selectDay(a);break;case "DW_Time2":b.selectTime(a);break}b.callback&&b.callback(b)}};function LASGetGridResponse(a){this.response=a;this.hasAxis=LASGetGridResponse_hasAxis;this.hasArange=LASGetGridResponse_hasArange;this.hasMenu=LASGetGridResponse_hasMenu;this.hasView=LASGetGridResponse_hasView;this.getAxis=LASGetGridResponse_getAxis;this.getLo=LASGetGridResponse_getLo;this.getHi=LASGetGridResponse_getHi;this.getDelta=LASGetGridResponse_getDelta;this.getSize=LASGetGridResponse_getSize;this.getUnits=LASGetGridResponse_getUnits;this.getID=LASGetGridResponse_getID;this.getMinuteInterval=
LASGetGridResponse_getMinuteInterval;this.getDisplayType=LASGetGridResponse_getDisplayType;this.getRenderFormat=LASGetGridResponse_getRenderFormat;this.getMenu=LASGetGridResponse_getMenu;if(a==null){a="getGrid.do returned a null response.";throw a;}else if(a.status!="ok"){a=a.error?a.error:"Unknown error in LASGetGridResponse.";throw a;}}
function LASGetGridResponse_getAxis(a){a=String(a).toLowerCase();for(var b=null,c=0;c<this.response.grid.axis.length;c++)if(this.response.grid.axis[c].type==a)b=this.response.grid.axis[c];return b}function LASGetGridResponse_hasView(a){for(var b=0;b<a.length;b++)if(!this.hasAxis(a.charAt(b)))return false;return true}function LASGetGridResponse_hasAxis(a){var b=false;if(this.getAxis(String(a).toLowerCase()))b=true;return b}
function LASGetGridResponse_hasArange(a){a=String(a).toLowerCase();var b=false;if(this.hasAxis(a))if(this.getAxis(a).arange)b=true;return b}function LASGetGridResponse_hasMenu(a){a=String(a).toLowerCase();var b=false;if(this.hasAxis(a))if(this.getAxis(a).v)b=true;return b}
function LASGetGridResponse_getLo(a){var b=String(a).toLowerCase(),c=null;if(b=="t")c=this.getAxis(b).lo;else if(this.hasMenu(a))c=this.getAxis(b).v[0];else{a=Number(this.getAxis(b).arange.start);c=Number(this.getAxis(b).arange.size);b=Number(this.getAxis(b).arange.step);c=b<0?a+(c-1)*b:a}return c}
function LASGetGridResponse_getHi(a){var b=String(a).toLowerCase(),c=null;if(b=="t")c=this.getAxis(b).hi?this.getAxis(b).hi:this.getAxis(b).lo;else if(this.hasMenu(a)){a=this.getAxis(b).v.length-1;c=this.getAxis(b).v[a]}else{a=Number(this.getAxis(b).arange.start);c=Number(this.getAxis(b).arange.size);b=Number(this.getAxis(b).arange.step);c=b<0?a:a+(c-1)*b}return c}
function LASGetGridResponse_getDelta(a){a=String(a).toLowerCase();var b=null;if(this.hasArange(a))b=this.getAxis(a).arange.step;return Number(b)}function LASGetGridResponse_getMinuteInterval(a){a=String(a).toLowerCase();var b=null;if(this.hasArange(a))b=Number(this.getAxis(a).minuteInterval);return b}function LASGetGridResponse_getSize(a){var b=String(a).toLowerCase(),c=null;if(this.hasArange(b))c=this.getAxis(b).arange.size;else if(this.hasMenu(a))c=this.getAxis(b).v.length;return Number(c)}
function LASGetGridResponse_getUnits(a){var b=null;a=String(a).toLowerCase();if(this.hasAxis(a))b=this.getAxis(a).units;return b}function LASGetGridResponse_getID(a){var b=null;a=String(a).toLowerCase();if(this.hasAxis(a))b=this.getAxis(a).display_type;return b}function LASGetGridResponse_getDisplayType(a){var b=String(a).toLowerCase(),c=null;if(this.hasAxis(a))if(this.getAxis(b).display_type)c=this.getAxis(b).display_type;return c}
function LASGetGridResponse_getRenderFormat(a){var b=null;switch(String(a).toLowerCase()){case "t":b="";if(this.getAxis("t").yearNeeded=="true")b+="Y";if(this.getAxis("t").monthNeeded=="true")b+="M";if(this.getAxis("t").dayNeeded=="true")b+="D";if(this.getAxis("t").hourNeeded=="true")b+="T";break}return b}
function LASGetGridResponse_getMenu(a){a=String(a).toLowerCase();var b=null,c=null;b=[];if(this.getAxis(a).v&&typeof this.getAxis(a).v=="object"&&!this.getAxis(a).v.label){c=this.getAxis(a).v;for(var e=0;e<c.length;e++)if(a=="t"){var f=String(c[e].content).toLowerCase();if(f=="jan")c[e].content="15-Jan";if(f=="feb")c[e].content="15-Feb";if(f=="mar")c[e].content="15-Mar";if(f=="apr")c[e].content="15-Apr";if(f=="may")c[e].content="15-May";if(f=="jun")c[e].content="15-Jun";if(f=="jul")c[e].content="15-Jul";
if(f=="aug")c[e].content="15-Aug";if(f=="sep")c[e].content="15-Sep";if(f=="oct")c[e].content="15-Oct";if(f=="nov")c[e].content="15-Nov";if(f=="dec")c[e].content="15-Dec";b[e]=new Array(c[e].label,c[e].content)}else b[e]=new Array(c[e],c[e])}else if(this.getAxis(a).v)b[0]=this.getAxis(a).v.label?new Array(this.getAxis(a).v.label,this.getAxis(a).v.content):new Array(this.getAxis(a).v,this.getAxis(a).v);return b};function LASGetCategoriesResponse(a){this.response=a;if(!this.response)return false;this.getDatasetID=LASGetCategoriesResponse_getDatasetID;this.getCategoryType=LASGetCategoriesResponse_getCategoryType;this.getCategorySize=LASGetCategoriesResponse_getCategorySize;this.getChild=LASGetCategoriesResponse_getChild;this.getChildrenType=LASGetCategoriesResponse_getChildrenType;this.getChildID=LASGetCategoriesResponse_getChildID;this.getChildDatasetID=LASGetCategoriesResponse_getChildDatasetID;this.getDatasetName=
LASGetCategoriesResponse_getDatasetName;this.getChildType=LASGetCategoriesResponse_getChildType;this.getChildByID=LASGetCategoriesResponse_getChildByID;this.getChildChildrenType=LASGetCategoriesResponse_getChildChildrenType;this.getChildName=LASGetCategoriesResponse_getChildName}function LASGetCategoriesResponse_getCategoryType(){return this.response.categories.category?this.response.categories.category[0]?this.response.categories.category[0].dataset?"dataset":"category":null:null}
function LASGetCategoriesResponse_getDatasetID(a){if(a==null)a=0;if(this.getCategoryType()=="dataset"){var b=0,c=this.response.categories.category[0].dataset.length;c||(c=1);for(d=0;d<c;d++)if(c==1)return this.response.categories.category[0].dataset.ID;else if(this.response.categories.category[0].dataset[d].variables)if(this.response.categories.category[0].dataset[d].variables.variable){lastct=b;b+=this.response.categories.category[0].dataset[d].variables.variable.length;if(a>=lastct&&a<b)return this.response.categories.category[0].dataset[d].ID}}else return"category"}
function LASGetCategoriesResponse_getDatasetName(){if(this.getCategoryType()=="dataset")if(this.response.categories.category[0].dataset.name)return this.response.categories.category[0].dataset.name;else{if(this.response.categories.category[0].name)return this.response.categories.category[0].name}else return"category"}
function LASGetCategoriesResponse_getCategorySize(){if(this.getCategoryType()=="dataset"){var a=0,b=this.response.categories.category[0].dataset.length;b||(b=1);for(i=0;i<b;i++)if(b==1){if(this.response.categories.category[0].dataset.variables.variable)a+=this.response.categories.category[0].dataset.variables.variable.length}else if(this.response.categories.category[0].dataset[i].variables)if(this.response.categories.category[0].dataset[i].variables.variable)a+=this.response.categories.category[0].dataset[i].variables.variable.length;
return a}else return this.response.categories[this.getCategoryType()]?this.response.categories[this.getCategoryType()].length:false}
function LASGetCategoriesResponse_getChild(a){if(this.getCategoryType()=="dataset"){var b=0,c=this.response.categories.category[0].dataset.length;c||(c=1);for(d=0;d<c;d++)if(c==1){if(this.response.categories.category[0].dataset.variables.variable)if(this.response.categories.category[0].dataset.variables.variable){lastct=b;b+=this.response.categories.category[0].dataset.variables.variable.length;if(a>=lastct&&a<b)return this.response.categories.category[0].dataset.variables.variable[a-lastct]}}else if(this.response.categories.category[0].dataset[d].variables)if(this.response.categories.category[0].dataset[d].variables.variable){lastct=
b;b+=this.response.categories.category[0].dataset[d].variables.variable.length;if(a>=lastct&&a<b)return this.response.categories.category[0].dataset[d].variables.variable[a-lastct]}}else this.getCategoryType();return this.response.categories[this.getCategoryType()][a]}function LASGetCategoriesResponse_getChildrenType(a){switch(this.getCategoryType()){case "category":return"categories";case "dataset":return"variables";default:return false}}
function LASGetCategoriesResponse_getChildType(a){switch(this.getChildChildrenType(a)){case "variables":return"dataset";case "categories":return"category";default:return false}}function LASGetCategoriesResponse_getChildChildrenType(a){return this.getChild(a).children?this.getChild(a).children:false}function LASGetCategoriesResponse_getChildID(a){if(this.getChild(a).ID)return this.getChild(a).ID}
function LASGetCategoriesResponse_getChildDatasetID(a){if(this.getChild(a).children_dsid)return this.getChild(a).children_dsid}function LASGetCategoriesResponse_getChildName(a){if(this.getChild(a).ID)return this.getChild(a).name}function LASGetCategoriesResponse_getChildByID(a){for(var b=0;b<this.getCategorySize();b++)if(this.getChildID(b)==a)return this.getChild(b)};function LASGetViewsResponse(a){this.response=a;if(!this.response)return false;this.getAllViews=LASGetViewsResponse_getAllViews;this.getViewCount=LASGetViewsResponse_getViewCount;this.getView=LASGetViewsResponse_getView;this.getViewID=LASGetViewsResponse_getViewID;this.getViewByID=LASGetViewsResponse_getViewByID;this.getViewName=LASGetViewsResponse_getViewName}function LASGetViewsResponse_getAllViews(){return this.response.views.view?this.response.views.view:null}
function LASGetViewsResponse_getViewCount(){return this.getAllViews()?this.getAllViews().length:-1}function LASGetViewsResponse_getView(a){return a>=0&&a<this.getViewCount()?this.getAllViews()[a]:null}function LASGetViewsResponse_getViewID(a){return this.getView(a)?this.getView(a).value:null}function LASGetViewsResponse_getViewByID(a){for(var b=0;b<this.getViewCount();b++)if(this.getView(b).value==a)return this.getView(b);return null}
function LASGetViewsResponse_getViewName(a){return this.getView(a)?this.getView(a).name:null};function LASGetOperationsResponse(a){this.response=a;if(!this.response)return false;this.getAllOperations=LASGetOperationsResponse_getAllOperations;this.getOperationCount=LASGetOperationsResponse_getOperationCount;this.getOperation=LASGetOperationsResponse_getOperation;this.getOperationID=LASGetOperationsResponse_getOperationID;this.getOperationByID=LASGetOperationsResponse_getOperationByID;this.getOperationName=LASGetOperationsResponse_getOperationName;this.getOperationsByView=LASGetOperationsResponse_getOperationsByView;
this.getOperationsByType=LASGetOperationsResponse_getOperationsByType;this.getOperationTypes=LASGetOperationsResponse_getOperationTypes;this.getAllOperationTypes=LASGetOperationsResponse_getAllOperationTypes;this.getAllIntervals=LASGetOperationsResponse_getAllIntervals;this.getOperationIntervals=LASGetOperationsResponse_getOperationIntervals;this.hasInterval=LASGetOperationsResponse_hasInterval}
function LASGetOperationsResponse_hasInterval(a,b){if(this.getOperationByID(a).region)if(this.getOperationByID(a).region.intervals)if(this.getOperationByID(a).region.intervals.length)for(var c=0;c<this.getOperationByID(a).region.intervals.length;c++){if(this.getOperationByID(a).region.intervals[c].name==b)return true}else return this.getOperationByID(a).region.intervals.name==b?true:false;else return false}
function LASGetOperationsResponse_getAllIntervals(){for(var a={},b=0;b<this.getOperationCount();b++)if(this.getOperation(b).region)if(this.getOperation(b).region.intervals)if(this.getOperation(b).region.intervals.length)for(var c=0;c<this.getOperation(b).region.intervals.length;c++)a[this.getOperation(b).region.intervals[c].name]||(a[this.getOperation(b).region.intervals[c].name]=true);else a[this.getOperation(b).region.intervals.name]||(a[this.getOperation(b).region.intervals.name]=true);return a}
function LASGetOperationsResponse_getOperationIntervals(a){var b={};if(this.getOperationByID(a).region)if(this.getOperationByID(a).region.intervals)if(this.getOperationByID(a).region.intervals.length)for(var c=0;c<this.getOperationByID(a).region.intervals.length;c++)b[this.getOperationByID(a).region.intervals[c].name]||(b[this.getOperationByID(a).region.intervals[c].name]=this.getOperationByID(a).region.intervals[c]);else if(!b[this.getOperationByID(a).region.intervals.name])b[this.getOperationByID(a).region.intervals.name]=
this.getOperationByID(a).region.intervals;return b}
function LASGetOperationsResponse_getOperationsByType(a){for(var b={},c=0;c<this.getOperationCount();c++)if(this.getOperation(c).region)if(this.getOperation(c).region.intervals)if(this.getOperation(c).region.intervals.length)for(var e=0;e<this.getOperation(c).region.intervals.length;e++){if(this.getOperation(c).region.intervals[e].type==a)b[this.getOperationID(c)]||(b[this.getOperationID(c)]=this.getOperation(c))}else if(this.getOperation(c).region.intervals.type==a)b[this.getOperationID(c)]||(b[this.getOperationID(c)]=
this.getOperation(c));return b}function LASGetOperationsResponse_getOperationTypes(a){var b={};if(this.getOperation(a).region)if(this.getOperation(a).region.intervals)if(this.getOperation(a).region.intervals.length)for(var c=0;c<this.getOperation(a).region.intervals.length;c++)b[this.getOperation(a).region.intervals[c].type]||(b[this.getOperation(a).region.intervals[c].type]=true);else b[this.getOperation(a).region.intervals.type]||(b[this.getOperation(a).region.intervals.type]=true);return b}
function LASGetOperationsResponse_getAllOperationTypes(a){var b={};for(a=0;a<this.getOperationCount();a++)for(var c in this.getOperationTypes(a))b[c]||(b[c]=true);return b}
function LASGetOperationsResponse_getOperationsByView(a){for(var b={},c=0;c<this.getOperationCount();c++)if(this.getOperation(c).region)if(this.getOperation(c).region.intervals)if(this.getOperation(c).region.intervals.interval){if(this.getOperation(c).region.intervals.interval.name==a)b[this.getOperationID(c)]||(b[this.getOperationID(c)]=this.getOperation(c))}else for(var e=0;e<this.getOperation(c).region.intervals.length;e++)if(this.getOperation(c).region.intervals[e].name==a)b[this.getOperationID(c)]||
(b[this.getOperationID(c)]=this.getOperation(c));return b}function LASGetOperationsResponse_getAllOperations(){return this.response.operations.operation?this.response.operations.operation:null}function LASGetOperationsResponse_getOperationCount(){return this.getAllOperations()?this.getAllOperations().length:-1}function LASGetOperationsResponse_getOperation(a){return a>=0&&a<this.getOperationCount()?this.getAllOperations()[a]:null}
function LASGetOperationsResponse_getOperationID(a){return this.getOperation(a)?this.getOperation(a).ID:null}function LASGetOperationsResponse_getOperationByID(a){for(var b=0;b<this.getOperationCount();b++)if(this.getOperation(b).ID==a)return this.getOperation(b);return null}function LASGetOperationsResponse_getOperationName(a){return this.getOperation(a)?this.getOperation(a).name:null};function LASGetOptionsResponse(a){this.response=a;if(!this.response)return false;this.getAllOptions=LASGetOptionsResponse_getAllOptions;this.getOptionCount=LASGetOptionsResponse_getOptionCount;this.getOption=LASGetOptionsResponse_getOption;this.getOptionID=LASGetOptionsResponse_getOptionID;this.getOptionByID=LASGetOptionsResponse_getOptionByID;this.getOptionName=LASGetOptionsResponse_getOptionName;this.getOptionType=LASGetOptionsResponse_getOptionType}
function LASGetOptionsResponse_getAllOptions(){return this.response.options.option?this.response.options.option:null}function LASGetOptionsResponse_getOptionCount(){return this.getAllOptions()?this.getAllOptions().length:-1}function LASGetOptionsResponse_getOption(a){return a>=0&&a<this.getOptionCount()?this.getAllOptions()[a]:null}function LASGetOptionsResponse_getOptionID(a){return this.getOption(a)?this.getOption(a).ID:null}
function LASGetOptionsResponse_getOptionByID(a){for(var b=0;b<this.getOptionCount();b++)if(this.getOption(b).ID==a)return this.getOption(b);return null}function LASGetOptionsResponse_getOptionName(a){return this.getOption(a)?this.getOption(a).title:null}function LASGetOptionsResponse_getOptionType(a){return this.getOption(a).menu?"menu":this.getOption(a).textfield?"text":null};function LASGetDataConstraintsResponse(a){this.response=a;if(!this.response)return false;this.getConstraintID=LASGetDataConstraintsResponse_getConstraintID;this.getConstraintType=LASGetDataConstraintsResponse_getConstraintType;this.getConstraintSize=LASGetDataConstraintsResponse_getConstraintSize;this.getChild=LASGetDataConstraintsResponse_getChild;this.getChildrenType=LASGetDataConstraintsResponse_getChildrenType;this.getChildID=LASGetDataConstraintsResponse_getChildID;this.getChildType=LASGetDataConstraintsResponse_getChildType;
this.getChildName=LASGetDataConstraintsResponse_getChildName}function LASGetDataConstraintsResponse_getConstraintType(){return this.response.DataConstraints.Constraint?this.response.DataConstraints.Constraint[0]?this.response.DataConstraints.Constraint[0].dataset?"dataset":"Constraint":null:null}function LASGetDataConstraintsResponse_getConstraintID(){return this.getConstraintType()=="dataset"?this.response.DataConstraints.Constraint[0].constraint.ID:"Constraint"}
function LASGetDataConstraintsResponse_getConstraintSize(){if(this.getConstraintType()=="dataset"){if(this.response.DataConstraints.Constraint[0].dataset.variables.variable)return this.response.DataConstraints.Constraint[0].dataset.variables.variable.length}else return this.response.DataConstraints[this.getConstraintType()]?this.response.DataConstraints[this.getConstraintType()].length:false}
function LASGetDataConstraintsResponse_getChild(a){if(this.getConstraintType()=="dataset")return this.response.DataConstraints.Constraint[0].dataset.variables.variable[a];else this.getConstraintType();return this.response.DataConstraints[this.getConstraintType()][a]}function LASGetDataConstraintsResponse_getChildrenType(a){switch(this.getConstraintType()){case "Constraint":return"DataConstraints";case "dataset":return"variables";default:return false}}
function LASGetDataConstraintsResponse_getChildType(a){switch(this.getChildChildrenType(a)){case "variables":return"dataset";case "DataConstraints":return"Constraint";default:return false}}function LASGetDataConstraintsResponse_getChildID(a){if(this.getChild(a).ID)return this.getChild(a).ID}function LASGetDataConstraintsResponse_getChildName(a){if(this.getChild(a).ID)return this.getChild(a).name};
