#!/bin/sh
testdir=t
template=OBJ-TEST.pl
kinds=`( cd $testdir ; echo [a-z]*.pl | sed -e 's/\.pl//g' )`
echo "These are the kinds: $kinds"
for obj in box simple list html ; do
    for kind in $kinds ; do
	( set -x ; ln -s $template t/$obj-$kind.t )
    done
done
