# Makefile for ShowTable.pm
#
#    Copyright (C) 1996,1997  Alan K. Stebbens <aks@sgi.com>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#

require 5.002;
use ExtUtils::MakeMaker;

WriteMakefile(
	'NAME'		=> 'Data::ShowTable',
	'VERSION'	=> '3.3',
	'EXE_FILES'	=> [ 'showtable' ],
	'dist'		=> { COMPRESS => 'gzip',
			     SUFFIX => '.gz', 
			   },
    );
