/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package gov.noaa.pmel.tmap.las.ui;

import gov.noaa.pmel.tmap.las.jdom.JDOMUtils;
import gov.noaa.pmel.tmap.las.jdom.LASAnnotations;
import gov.noaa.pmel.tmap.las.jdom.LASConfig;
import gov.noaa.pmel.tmap.las.product.server.InitThread;
import gov.noaa.pmel.tmap.las.product.server.LASConfigPlugIn;

import java.io.File;
import java.io.IOException;
import java.util.Enumeration;
import java.util.Iterator;
import java.util.Map;

import javax.servlet.ServletContext;
import javax.servlet.http.Cookie;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.log4j.LogManager;
import org.apache.log4j.Logger;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 01-08-2007
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class GetAnnotations extends ConfigService {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	private static Logger log = LogManager.getLogger(GetAnnotations.class.getName());
	public ActionForward execute(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) throws Exception {    
		log.info("START: "+request.getRequestURL());
		LASConfig lasConfig = (LASConfig)servlet.getServletContext().getAttribute(LASConfigPlugIn.LAS_CONFIG_KEY);
		LASAnnotations lasAnnotations = new LASAnnotations();
		String template = request.getParameter("template");
		if ( template == null ) {
			template = "annotations.vm";
		}
		String file = request.getParameter("file");
		if ( file != null ) {
			try {
				File f = new File(lasConfig.getOutputDir()+File.separator+file);
				JDOMUtils.XML2JDOM(f, lasAnnotations);
			} catch (IOException e) {
				// Send it on to the template empty.
			}

		}
		// Put these objects in the context so the output template can use them.
		request.setAttribute("las_annotations", lasAnnotations);
		log.info("END:   "+request.getRequestURL());
		return new ActionForward("/productserver/templates/"+template);
	}
}