/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package gov.noaa.pmel.tmap.las.ui;

import gov.noaa.pmel.tmap.las.jdom.JDOMUtils;
import gov.noaa.pmel.tmap.las.jdom.LASAnnotations;
import gov.noaa.pmel.tmap.las.jdom.LASConfig;
import gov.noaa.pmel.tmap.las.product.server.InitThread;
import gov.noaa.pmel.tmap.las.product.server.LASConfigPlugIn;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

import javax.servlet.ServletContext;
import javax.servlet.http.Cookie;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.log4j.Logger;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 01-08-2007
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class GetAnnotations extends ConfigService {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	private static Logger log = Logger.getLogger(GetAnnotations.class.getName());
	public ActionForward execute(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) throws Exception {    
		log.info("START: "+request.getRequestURL());
        LASConfig lasConfig = (LASConfig)servlet.getServletContext().getAttribute(LASConfigPlugIn.LAS_CONFIG_KEY);
        request.setAttribute("base_server_url", lasConfig.getBaseServerURL());
	
		String template = request.getParameter("template");
		if ( template == null ) {
			template = "annotations.vm";
		}
		String[] files = request.getParameterValues("file");
		String[] images = request.getParameterValues("image");
		
		if ( files != null ) {
			if ( files.length == 1 ) {			
				LASAnnotations lasAnnotations = new LASAnnotations();
				loadAnnotations(files[0], lasAnnotations);
				request.setAttribute("las_annotations", lasAnnotations);
				
				if ( images != null && !images[0].equals("") ) {
					request.setAttribute("image_file", images[0]);
				}
			} else {
				List<LASAnnotations> annotations = new ArrayList<LASAnnotations>();
				for ( int i = 0; i < files.length; i++ ) {
					LASAnnotations lasAnnotations = new LASAnnotations();
					loadAnnotations(files[i], lasAnnotations);
					annotations.add(lasAnnotations);
				}
				request.setAttribute("las_annotation_files", annotations);
				if ( images != null && !images[0].equals("") ) {
					request.setAttribute("image_files", images);
				}
			}
			log.info("END:   "+request.getRequestURL());
			return new ActionForward("/productserver/templates/"+template);
		} else {
			LASAnnotations lasAnnotations = new LASAnnotations();
			lasAnnotations.setDatasetTitle("Error processing annotations file.");
			request.setAttribute("las_annotations", lasAnnotations);
			log.error("Unable to process annontations.");
			log.info("END:   "+request.getRequestURL());
			return new ActionForward("/productserver/templates/"+template);
		}
	}
	private void loadAnnotations(String file, LASAnnotations lasAnnotations) {
		try {
			LASConfig lasConfig = (LASConfig)servlet.getServletContext().getAttribute(LASConfigPlugIn.LAS_CONFIG_KEY);
			if ( file != null ) {
				File f = new File(lasConfig.getOutputDir()+File.separator+file);
				JDOMUtils.XML2JDOM(f, lasAnnotations);
			}
			// Put these objects in the context so the output template can use them.
		} catch ( Exception e ) {
			lasAnnotations.clear();
			lasAnnotations.setDatasetTitle("Error processing annotations file.");
			log.error("Unable to process annontations."+e.getMessage());			
		}
	}
}