/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package gov.noaa.pmel.tmap.las.ui;

import gov.noaa.pmel.tmap.las.jdom.LASConfig;
import gov.noaa.pmel.tmap.las.product.server.InitThread;
import gov.noaa.pmel.tmap.las.product.server.LASConfigPlugIn;

import java.util.Enumeration;
import java.util.Iterator;
import java.util.Map;

import javax.servlet.ServletContext;
import javax.servlet.http.Cookie;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.log4j.Logger;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 01-08-2007
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class GetUI7 extends ConfigService {
    /*
     * Generated Methods
     */

    /** 
     * Method execute
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @return ActionForward
     */
    private static Logger log = Logger.getLogger(GetUI.class.getName());
    public ActionForward execute(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) throws Exception {    
    	ServletContext context = (ServletContext) servlet.getServletContext();
        String lazy_start = (String) context.getAttribute(LASConfigPlugIn.LAS_LAZY_START_KEY);
        String data_url = request.getParameter("data_url");
        LASConfig lasConfig = (LASConfig)servlet.getServletContext().getAttribute(LASConfigPlugIn.LAS_CONFIG_KEY);
        if ( lazy_start != null && lazy_start.equals("true") ) {
        	// Start the initialization and forward to lazy start page
        	InitThread thread = new InitThread(context);
        	thread.start();
        	return mapping.findForward("lazy_start");
        } else {
        	// forward to the UI
        	
        	if ( data_url != null && !data_url.equals("") ) {
        		String ids = lasConfig.getIDs(data_url);
        		response.sendRedirect("getUI.do?"+ids);
        	} 
        	return new ActionForward("/productserver/templates/V7UI.vm");
        }
    }
}
