/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package gov.noaa.pmel.tmap.las.product.server;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-26-2007
 * 
 * XDoclet definition:
 * @struts.form name="ProgressForm"
 */
public class ProgressForm extends ActionForm {
    /*
     * Generated fields
     */

    /** email property */
    private String email;

    /*
     * Generated Methods
     */

    /** 
     * Method reset
     * @param mapping
     * @param request
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        
    }

    /** 
     * Returns the email.
     * @return String
     */
    public String getEmail() {
        return email;
    }

    /** 
     * Set the email.
     * @param email The email to set
     */
    public void setEmail(String email) {
        this.email = email;
    }
}