/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package gov.noaa.pmel.tmap.las.product.server;


/** 
 * MyEclipse Struts
 * Creation date: 03-26-2007
 * 
 * XDoclet definition:
 * @struts.form name="ProgressForm"
 */
public class ProgressForm {
    /*
     * Generated fields
     */

    /** email property */
    private String email;

    /*
     * Generated Methods
     */


    /** 
     * Returns the email.
     * @return String
     */
    public String getEmail() {
        return email;
    }

    /** 
     * Set the email.
     * @param email The email to set
     */
    public void setEmail(String email) {
        this.email = email;
    }
}